# MAIN_HAND — attack

[[item]]
    code = "sword"
    slots = ["MAIN_HAND"]
    health = 0
    critChance = 2
    dodgeChance = 2
    critMultiplier = 0.05
    speed = 15
    baseThreat = 8

    [item.attack]
    attackType = "SLASH"
    range = 1
    attack = 300

    [item.locales.RU]
    text = "Меч"
    form = "MASCULINE"

[[item]]
    code = "rapier"
    slots = ["MAIN_HAND"]
    health = 0
    critChance = 4
    dodgeChance = 5
    critMultiplier = 0.08
    speed = 20
    baseThreat = 4

    [item.attack]
    attackType = "PIERCE"
    range = 1
    attack = 285

    [item.locales.RU]
    text = "Рапира"
    form = "FEMININE"

[[item]]
    code = "mace"
    slots = ["MAIN_HAND"]
    health = 0
    critChance = 2
    dodgeChance = 1
    critMultiplier = 0.05
    speed = 15
    baseThreat = 12

    [item.attack]
    attackType = "BLUNT"
    range = 1
    attack = 298

    [item.locales.RU]
    text = "Булава"
    form = "FEMININE"

[[item]]
    code = "spear"
    slots = ["MAIN_HAND"]
    health = 0
    critChance = 3
    dodgeChance = 2
    critMultiplier = 0.05
    speed = 10
    baseThreat = 5

    [item.attack]
    attackType = "PIERCE"
    range = 2
    attack = 310

    [item.locales.RU]
    text = "Копьё"
    form = "NEUTER"

[[item]]
    code = "staff"
    slots = ["MAIN_HAND"]
    health = 0
    critChance = 3
    dodgeChance = 1
    critMultiplier = 0.08
    speed = 10
    baseThreat = 5

    [item.attack]
    attackType = "MAGICAL"
    range = 3
    attack = 310

    [item.locales.RU]
    text = "Посох"
    form = "MASCULINE"

[[item]]
    code = "bow"
    slots = ["MAIN_HAND", "OFF_HAND"]
    health = 0
    critChance = 4
    dodgeChance = 2
    critMultiplier = 0.05
    speed = 35
    baseThreat = 4

    [item.attack]
    attackType = "PIERCE"
    range = 2
    attack = 360

    [item.locales.RU]
    text = "Лук"
    form = "MASCULINE"

[[item]]
    code = "longbow"
    slots = ["MAIN_HAND", "OFF_HAND"]
    health = 0
    critChance = 3
    dodgeChance = 1
    critMultiplier = 0.05
    speed = 31
    baseThreat = 5

    [item.attack]
    attackType = "PIERCE"
    range = 3
    attack = 380

    [item.locales.RU]
    text = "Длинный Лук"
    form = "MASCULINE"

[[item]]
    code = "crossbow"
    slots = ["MAIN_HAND", "OFF_HAND"]
    health = 0
    critChance = 5
    dodgeChance = 1
    critMultiplier = 0.08
    speed = 35
    baseThreat = 8

    [item.attack]
    attackType = "BLUNT"
    range = 4
    attack = 370

    [item.locales.RU]
    text = "Арбалет"
    form = "MASCULINE"

[[item]]
    code = "two_handed_sword"
    slots = ["MAIN_HAND", "OFF_HAND"]
    health = 0
    critChance = 4
    dodgeChance = 1
    critMultiplier = 0.1
    speed = 25
    baseThreat = 10

    [item.attack]
    attackType = "SLASH"
    range = 1
    attack = 400

    [item.locales.RU]
    text = "Двуручный Меч"
    form = "MASCULINE"

[[item]]
    code = "sledgehammer"
    slots = ["MAIN_HAND", "OFF_HAND"]
    health = 0
    critChance = 2
    dodgeChance = 0
    critMultiplier = 0.05
    speed = 20
    baseThreat = 12

    [item.attack]
    attackType = "BLUNT"
    range = 1
    attack = 415

    [item.locales.RU]
    text = "Кувалда"
    form = "FEMININE"

[[item]]
    code = "halberd"
    slots = ["MAIN_HAND", "OFF_HAND"]
    health = 0
    critChance = 3
    dodgeChance = 0
    critMultiplier = 0.05
    speed = 25
    baseThreat = 10

    [item.attack]
    attackType = "PIERCE"
    range = 2
    attack = 398

    [item.locales.RU]
    text = "Алебарда"
    form = "FEMININE"

# OFF_HAND — attack or defense

[[item]]
    code = "shortsword"
    slots = ["OFF_HAND"]
    health = 0
    critChance = 2
    dodgeChance = 2
    critMultiplier = 0.05
    speed = 25
    baseThreat = 2

    [item.attack]
    attackType = "SLASH"
    range = 1
    attack = 50

    [item.locales.RU]
    text = "Короткий Меч"
    form = "MASCULINE"

[[item]]
    code = "club"
    slots = ["OFF_HAND"]
    health = 0
    critChance = 1
    dodgeChance = 1
    critMultiplier = 0.03
    speed = 25
    baseThreat = 8

    [item.attack]
    attackType = "BLUNT"
    range = 1
    attack = 50

    [item.locales.RU]
    text = "Дубина"
    form = "FEMININE"

[[item]]
    code = "dagger"
    slots = ["OFF_HAND"]
    health = 0
    critChance = 5
    dodgeChance = 1
    critMultiplier = 0.1
    speed = 18
    baseThreat = 1

    [item.attack]
    attackType = "SLASH"
    range = 1
    attack = 42

    [item.locales.RU]
    text = "Кинжал"
    form = "MASCULINE"

[[item]]
    code = "dirk"
    slots = ["OFF_HAND"]
    health = 0
    critChance = 2
    dodgeChance = 5
    critMultiplier = 0.05
    speed = 28
    baseThreat = 4

    [item.attack]
    attackType = "PIERCE"
    range = 1
    attack = 52

    [item.locales.RU]
    text = "Кортик"
    form = "MASCULINE"

[[item]]
    code = "orb"
    slots = ["OFF_HAND"]
    health = 0
    critChance = 2
    dodgeChance = 1
    critMultiplier = 0.05
    speed = 22
    baseThreat = 2

    [item.attack]
    attackType = "MAGICAL"
    range = 2
    attack = 50

    [item.locales.RU]
    text = "Сфера"
    form = "FEMININE"

[[item]]
    code = "buckler"
    slots = ["OFF_HAND"]
    health = 160
    critChance = 0
    dodgeChance = 4
    critMultiplier = 0
    speed = 28
    baseThreat = 0

    [item.defense]
    defenseType = "CLOTH"
    defense = 10

    [item.locales.RU]
    text = "Баклер"
    form = "MASCULINE"

[[item]]
    code = "shield"
    slots = ["OFF_HAND"]
    health = 280
    critChance = 0
    dodgeChance = 2
    critMultiplier = 0
    speed = 20
    baseThreat = 0

    [item.defense]
    defenseType = "LEATHER"
    defense = 16

    [item.locales.RU]
    text = "Щит"
    form = "MASCULINE"

[[item]]
    code = "tower_shield"
    slots = ["OFF_HAND"]
    health = 340
    critChance = 0
    dodgeChance = 0
    critMultiplier = 0
    speed = 12
    baseThreat = 8

    [item.defense]
    defenseType = "PLATE"
    defense = 32

    [item.locales.RU]
    text = "Башенный Щит"
    form = "MASCULINE"

[[item]]
    code = "tome"
    slots = ["OFF_HAND"]
    health = 250
    critChance = 0
    dodgeChance = 0
    critMultiplier = 0
    speed = 26
    baseThreat = 0

    [item.defense]
    defenseType = "ARCANE"
    defense = 22

    [item.locales.RU]
    text = "Том"
    form = "MASCULINE"

# BODY — defense

[[item]]
    code = "robe"
    slots = ["BODY"]
    health = 500
    critChance = 1
    dodgeChance = 1
    critMultiplier = 0.05
    speed = 38
    baseThreat = 1

    [item.defense]
    defenseType = "CLOTH"
    defense = 32

    [item.locales.RU]
    text = "Мантия"
    form = "FEMININE"

[[item]]
    code = "cuirass"
    slots = ["BODY"]
    health = 680
    critChance = 0
    dodgeChance = 0
    critMultiplier = 0
    speed = 16
    baseThreat = 12

    [item.defense]
    defenseType = "PLATE"
    defense = 64

    [item.locales.RU]
    text = "Кираса"
    form = "FEMININE"

[[item]]
    code = "breastplate"
    slots = ["BODY"]
    health = 600
    critChance = 1
    dodgeChance = 2
    critMultiplier = 0.05
    speed = 26
    baseThreat = 2

    [item.defense]
    defenseType = "LEATHER"
    defense = 48

    [item.locales.RU]
    text = "Нагрудник"
    form = "MASCULINE"

[[item]]
    code = "wizard_robe"
    slots = ["BODY"]
    health = 510
    critChance = 1
    dodgeChance = 1
    critMultiplier = 0.05
    speed = 32
    baseThreat = 1

    [item.defense]
    defenseType = "ARCANE"
    defense = 58

    [item.locales.RU]
    text = "Магическая Мантия"
    form = "FEMININE"

# PANTS — defense

[[item]]
    code = "cloth_chausses"
    slots = ["PANTS"]
    health = 230
    critChance = 1
    dodgeChance = 1
    critMultiplier = 0.05
    speed = 32
    baseThreat = 0

    [item.defense]
    defenseType = "CLOTH"
    defense = 12

    [item.locales.RU]
    text = "Тканевые Шоссы"
    form = "PLURAL"

[[item]]
    code = "leather_chausses"
    slots = ["PANTS"]
    health = 340
    critChance = 1
    dodgeChance = 1
    critMultiplier = 0.05
    speed = 24
    baseThreat = 1

    [item.defense]
    defenseType = "LEATHER"
    defense = 18

    [item.locales.RU]
    text = "Кожаные Шоссы"
    form = "PLURAL"

[[item]]
    code = "greaves"
    slots = ["PANTS"]
    health = 420
    critChance = 0
    dodgeChance = 0
    critMultiplier = 0
    speed = 14
    baseThreat = 8

    [item.defense]
    defenseType = "PLATE"
    defense = 36

    [item.locales.RU]
    text = "Латные Поножи"
    form = "PLURAL"

[[item]]
    code = "arcane_chausses"
    slots = ["PANTS"]
    health = 280
    critChance = 1
    dodgeChance = 1
    critMultiplier = 0.05
    speed = 28
    baseThreat = 0

    [item.defense]
    defenseType = "ARCANE"
    defense = 22

    [item.locales.RU]
    text = "Зачарованные Шоссы"
    form = "PLURAL"

# SHOES — defense

[[item]]
    code = "cloth_boots"
    slots = ["SHOES"]
    health = 120
    critChance = 1
    dodgeChance = 1
    critMultiplier = 0.05
    speed = 26
    baseThreat = 0

    [item.defense]
    defenseType = "CLOTH"
    defense = 7

    [item.locales.RU]
    text = "Тканевые Сапоги"
    form = "PLURAL"

[[item]]
    code = "boots"
    slots = ["SHOES"]
    health = 220
    critChance = 1
    dodgeChance = 2
    critMultiplier = 0.05
    speed = 18
    baseThreat = 1

    [item.defense]
    defenseType = "LEATHER"
    defense = 10

    [item.locales.RU]
    text = "Сапоги"
    form = "PLURAL"

[[item]]
    code = "sabatons"
    slots = ["SHOES"]
    health = 280
    critChance = 0
    dodgeChance = 0
    critMultiplier = 0
    speed = 10
    baseThreat = 6

    [item.defense]
    defenseType = "PLATE"
    defense = 22

    [item.locales.RU]
    text = "Латные Сапоги"
    form = "PLURAL"

[[item]]
    code = "arcane_boots"
    slots = ["SHOES"]
    health = 160
    critChance = 1
    dodgeChance = 1
    critMultiplier = 0.05
    speed = 22
    baseThreat = 0

    [item.defense]
    defenseType = "ARCANE"
    defense = 14

    [item.locales.RU]
    text = "Магические Сапоги"
    form = "PLURAL"

# HELMET — defense

[[item]]
    code = "hood"
    slots = ["HELMET"]
    health = 120
    critChance = 1
    dodgeChance = 1
    critMultiplier = 0.05
    speed = 24
    baseThreat = 1

    [item.defense]
    defenseType = "CLOTH"
    defense = 7

    [item.locales.RU]
    text = "Капюшон"
    form = "MASCULINE"

[[item]]
    code = "leather_helm"
    slots = ["HELMET"]
    health = 220
    critChance = 1
    dodgeChance = 0
    critMultiplier = 0.05
    speed = 16
    baseThreat = 1

    [item.defense]
    defenseType = "LEATHER"
    defense = 10

    [item.locales.RU]
    text = "Кожаный Шлем"
    form = "MASCULINE"

[[item]]
    code = "great_helm"
    slots = ["HELMET"]
    health = 280
    critChance = 0
    dodgeChance = 0
    critMultiplier = 0
    speed = 10
    baseThreat = 6

    [item.defense]
    defenseType = "PLATE"
    defense = 22

    [item.locales.RU]
    text = "Латный Шлем"
    form = "MASCULINE"

[[item]]
    code = "circlet"
    slots = ["HELMET"]
    health = 160
    critChance = 4
    dodgeChance = 1
    critMultiplier = 0.1
    speed = 20
    baseThreat = 1

    [item.defense]
    defenseType = "ARCANE"
    defense = 14

    [item.locales.RU]
    text = "Диадема"
    form = "FEMININE"

# GLOVES — defense

[[item]]
    code = "cloth_gloves"
    slots = ["GLOVES"]
    health = 120
    critChance = 1
    dodgeChance = 1
    critMultiplier = 0.05
    speed = 26
    baseThreat = 1

    [item.defense]
    defenseType = "CLOTH"
    defense = 7

    [item.locales.RU]
    text = "Перчатки"
    form = "PLURAL"

[[item]]
    code = "leather_gloves"
    slots = ["GLOVES"]
    health = 220
    critChance = 1
    dodgeChance = 0
    critMultiplier = 0.05
    speed = 16
    baseThreat = 1

    [item.defense]
    defenseType = "LEATHER"
    defense = 10

    [item.locales.RU]
    text = "Кожаные Перчатки"
    form = "PLURAL"

[[item]]
    code = "gauntlets"
    slots = ["GLOVES"]
    health = 280
    critChance = 0
    dodgeChance = 0
    critMultiplier = 0
    speed = 10
    baseThreat = 4

    [item.defense]
    defenseType = "PLATE"
    defense = 22

    [item.locales.RU]
    text = "Латные Рукавицы"
    form = "PLURAL"

[[item]]
    code = "arcane_gloves"
    slots = ["GLOVES"]
    health = 160
    critChance = 1
    dodgeChance = 1
    critMultiplier = 0.05
    speed = 22
    baseThreat = 0

    [item.defense]
    defenseType = "ARCANE"
    defense = 14

    [item.locales.RU]
    text = "Магические Перчатки"
    form = "PLURAL"
