[[event]]
id = 1
duration = "PT15M"
isEnabled = true

[event.raid]
template = "SINGLE_BOSS"
name = "Сварливая фея"

[[event.locales]]
language = "RU"
intro = "О нет, еще одна деревня пострадала от проказ Сварливой феи!"
description = "Вода в реках и колодцах стала соленой, а коровы — разумными и теперь бунтуют против доения. Надо помочь крестьянам и одолеть гадкую крылатую хулиганку!"

[[event.locales]]
language = "EN"
intro = "Oh no, another village has suffered from the pranks of a Grumpy fairy!"
description = "The water in rivers and wells has become salty, and cows have become intelligent and are now rebelling against milking. We need to help the peasants and defeat the ugly winged hooligan!"

[[event]]
id = 2
duration = "PT30M"
isEnabled = true

[event.raid]
template = "SINGLE_BOSS"
name = "Флейтист-крысолов"

[[event.locales]]
language = "RU"
intro = "С рождаемостью и так неважно, так ещё и Флейтист-крысолов увёл всех детей из деревни."
description = "Говорят, что ему не заплатили за вивисекцию усатых вредителей, так что он жестоко наказал местных — и завёл свою угрюмую трель, зачаровав всех детей. Флейтист увел бедняжек, и отчаявшиеся родители молят героев о помощи!"

[[event.locales]]
language = "EN"
intro = "With the birth rate and is bad, so also the Piper-piper took all the children out of the village."
description = "They say that he was not paid for the vivisection of mustachioed pests, so he severely punished the locals — and started his sullen trill, charming all the children. The flutist has taken the poor things away, and the desperate parents are begging the heroes for help!"

[[event]]
id = 3
duration = "PT20M"
isEnabled = true

[event.raid]
template = "SINGLE_BOSS"
name = "Гарпия-ворона"

[[event.locales]]
language = "RU"
intro = "Гарпия-ворона? Гарпия-ворона! Выглядит как ощипанная курица, любит всё блестящее, как ворона."
description = "Знатные дамы ошалели: в столице уже не осталось брошек и вышитых золотом шляпок. Как, спрашивается, вести привычную жизнь гостиных? Дворянки подали коллективную жалобу, так что мэру пришлось заняться поисками отважных курощупов."

[[event.locales]]
language = "EN"
intro = "A crow harpy? The harpy crow! Looks like a plucked chicken, loves everything shiny, like a crow."
description = "The noble ladies were stunned: there were no brooches and gold-embroidered hats left in the capital. How, one may ask, to lead the usual life of living rooms? The noblewomen filed a collective complaint, so the mayor had to look for brave kuroschupov."

[[event]]
id = 4
duration = "PT45M"
isEnabled = true

[event.raid]
template = "SINGLE_BOSS"
name = "Кротокракен"

[[event.locales]]
language = "RU"
intro = "Неудачные эксперименты с кротовухой разбудили Кротокракена!"
description = "После того как в городах стала популярна сомнительная настойка, винная индустрия переобулась и начала активно расхищать земли Кротокракена, уничтожая его народ, за что зверь восстал и начал свою подрывную деятельность. Остановите Крота, а потом уже и людям надаёте!"

[[event.locales]]
language = "EN"
intro = "Unsuccessful experiments with the krotovuha woke up the Krotokraken!"
description = "After the dubious tincture became popular in the cities, the wine industry changed its shoes and began actively plundering the lands of the Krotokraken, destroying its people, for which the beast rebelled and began its subversive activities. Stop the Mole, and then you'll kick people!"

[[event]]
id = 5
duration = "PT35M"
isEnabled = true

[event.raid]
template = "ENEMY_GROUP"
name = "Миконид"

[[event.locales]]
language = "RU"
intro = "Подлючие микониды! Откуда у них разум?!"
description = "Грибники в опасности! Микониды действуют хитро: сначала награждают грибников едким душком на ногах, а после заселяются в их свободные дома! От зловонного запаха ног умерло уже 6 семей! Помогите, люди добрые!"

[[event.locales]]
language = "EN"
intro = "Prickly myconids! Where did they get their mind from?!"
description = "Mushroom pickers are in danger! The Myconids act cunningly: first they reward mushroom pickers with a pungent smell on their feet, and then they move into their vacant houses! 6 families have already died from the fetid smell of feet! Help, kind people!"

[[event]]
id = 6
duration = "PT30M"
isEnabled = true

[event.raid]
template = "SINGLE_BOSS"
name = "Мимик-осеменитель"

[[event.locales]]
language = "RU"
intro = "Спасите! От Мимика! Он же Гоша, он же Гога, он же муж!"
description = """
Мужья города в отчаянии! Жёны не перестают рожать! Счастье для демографии обернулось загадочной трагедией для семей города. Женщины утверждают, что проводят ночь с мужьями, а мужья утверждают, что спят с пивом, — где же правда?
Возможно, стоит подстеречь “мужа на час” и решить всё на месте!"""

[[event.locales]]
language = "EN"
intro = "Save me! From the Mimic! He's Gosha, he's Goga, he's a husband!"
description = """
The husbands of the city are in despair! Wives don't stop giving birth! Happiness for the demography turned into a mysterious tragedy for the families of the city. Women claim to spend the night with their husbands, and husbands claim to sleep with beer — where is the truth?
Perhaps it's worth lying in wait for the “husband for an hour" and solve everything on the spot!"""

[[event]]
id = 7
duration = "PT30M"
isEnabled = true

[event.raid]
template = "SINGLE_BOSS"
name = "Некромант"

[[event.locales]]
language = "RU"
intro = "Преступление и наказание и зомби"
description = "В городе недалеко от столицы два пьяных зомби напали на торговца лепёшками. Инцидент произошел поздно ночью, кто накормил зомби мясом с вином и зачем ему это нужно - не установлено. Местные власти призывают смельчаков отловить негодяя!"

[[event.locales]]
language = "EN"
intro = "Crime and punishment and zombies"
description = "In a city near the capital, two drunken zombies attacked a tortilla vendor. The incident occurred late at night, who fed the zombie meat with wine and why he needed it is not established. Local authorities are calling on the brave souls to catch the scoundrel!"

[[event]]
id = 8
duration = "PT30M"
isEnabled = true

[event.raid]
template = "SINGLE_BOSS"
name = "Подружка невесты Загтмой"

[[event.locales]]
language = "RU"
intro = "Подружка невесты та ещё...монстр!"
description = "Городская сумасшедшая окончательно сошла с ума. Мало того, что она выходит замуж за пень, так и подружку выбрала себе монстра! Остановите свадьбу пока прожорливое растение не сожрало и невесту, и город!"

[[event.locales]]
language = "EN"
intro = "The bridesmaid is... a monster!"
description = "The city madwoman has finally gone crazy. Not only is she getting married to a stump, but she chose a monster for her girlfriend! Stop the wedding before the voracious plant devours both the bride and the city!"

[[event]]
id = 9
duration = "PT30M"
isEnabled = true

[event.raid]
template = "ENEMY_GROUP"
name = "Культ ретроградного Ашанна"

[[event.locales]]
language = "RU"
intro = "Остановите Ашанн!"
description = "Ашанн и его приспешники угрожают всем ретроградной Луной Дурных Предзнаменований и, если люди хотят спастись, то им нужно внести некую сумму на счёт культа и тогда беды их минуют. Бедный народ! Соберите людей и в бой!"

[[event.locales]]
language = "EN"
intro = "Stop Ashann!"
description = "Ashann and his henchmen threaten everyone with a retrograde Moon of Bad Omens and if people want to be saved, then they need to deposit a certain amount to the cult account and then their troubles will pass. Poor people! Gather people and fight!"

[[event]]
id = 10
duration = "PT30M"
isEnabled = true

[event.raid]
template = "ENEMY_GROUP"
name = "Огры у башни"

[[event.locales]]
language = "RU"
intro = "Заказ от чародея Вальдемара"
description = "Срочно нуждаюсь в охране башни от нападения огров! Их барабаны, псы и воришки не дают мне спать! Они вечно пытаются расшатать мою башню! Остановите их! Наградой будет бесценный опыт и немного золота"

[[event.locales]]
language = "EN"
intro = "An order from the wizard Valdemar"
description = "I urgently need to protect the tower from an ogre attack! Their drums, dogs and thieves don't let me sleep! They're always trying to shake my tower! Stop them! The reward will be invaluable experience and a little gold"

[[event]]
id = 11
duration = "PT30M"
isEnabled = true

[event.raid]
template = "ENEMY_GROUP"
name = "Стая маггусей"

[[event.locales]]
language = "RU"
intro = "Караул! Маггуси терроризируют деревню!"
description = """
Переизбыток магии свёл некоторых гусей с ума! Они сбиваются в стаи и нападают на всех подряд. Периодически жертвами становятся даже другие гуси! Крестьяне боятся за свою жизнь и отказываются выходить работать в поля. Остановите этих тварей!
Кстати, таверны Крезара с радостью заплатят вам за свежие маггусиные тушки."""

[[event.locales]]
language = "EN"
intro = "Help! Maggeese are terrorizing the village!"
description = """
An overabundance of magic has driven some geese crazy! They get together in packs and attack everyone. Periodically, even other geese become victims! The peasants are afraid for their lives and refuse to go out to work in the fields. Stop these creatures!
By the way, the Krezar taverns, will gladly pay you for fresh maggoose carcasses."""

[[event]]
id = 12
duration = "PT30M"
isEnabled = true

[event.raid]
template = "SINGLE_BOSS"
name = "Соломенное чучело"

[[event.locales]]
language = "RU"
intro = "Появилось соломенное чучело!"
description = "Посреди площади появилось уродливое чучело из соломы. Оно вызывает соломеновороний ураган, солома и вороны везде! В носах, ушах, менее удачливые люди погибают от множественных соломеновороных ран. Помогите городу и возвратите чучело в огородный ад!"

[[event.locales]]
language = "EN"
intro = "A straw scarecrow appeared!"
description = "An ugly stuffed straw man appeared in the middle of the square. It causes a straw crow hurricane, straw and crows everywhere! In the noses, ears, less fortunate people die from multiple straw wounds. Help the city and return the scarecrow to the garden hell!"

[[event]]
id = 13
duration = "PT30M"
isEnabled = true

[event.raid]
template = "SINGLE_BOSS"
name = "Мудрый волк"

[[event.locales]]
language = "RU"
intro = "Мудрый волк снова мудрит."
description = 'С недавних пор охотники, вернувшиеся из леса, ведут себя странно. Они заявляют, что не выступают в цирке и мучают горожан советами: "Не важно кто, важно кто!", "Лучше попробовать, чем не попробовать", "Любят тихо, громко только предают". Расправьтесь с причиной этого безумства!'

[[event.locales]]
language = "EN"
intro = "The wise wolf is wise again."
description = "Recently, hunters who have returned from the forest have been behaving strangely. They claim that they do not perform in the circus and torment the townspeople with advice: \"It doesn't matter who, it's important who!\", \"It's better to try than not to try\", \"They love quietly, loudly only betray\". Deal with the cause of this madness!"

[[event]]
id = 14
duration = "PT30M"
isEnabled = true

[event.raid]
template = "ENEMY_GROUP"
name = "Отходники-водовороты"

[[event.locales]]
language = "RU"
intro = "Водовороты в отхожем месте!"
description = 'Отхожее место больше не безопасно! Стоит гражданину только присесть, как дыра в полу резко расширяется и он падает в бездну. Единственный выживший находится в шоковом состоянии и повторяет одну фразу: "Я не умру в туалете!". Ситуация экстренная! Спасите людей от ужасного монстра, покусившегося на святое!'

[[event.locales]]
language = "EN"
intro = "Whirlpools in the latrine!"
description = 'The latrine is no longer safe! As soon as a citizen sits down, the hole in the floor expands dramatically and he falls into the abyss. The only survivor is in a state of shock and repeats one phrase: "I will not die in the toilet!". The situation is urgent! Save people from a terrible monster that has encroached on the holy!'

[[event]]
id = 15
duration = "PT30M"
isEnabled = true

[event.raid]
template = "ENEMY_GROUP"
name = "Долгоносик"

[[event.locales]]
language = "RU"
intro = "Наш урожай пожрал долгоносик!"
description = "Внезапная напасать обрушилась на деревни южнее Крезара: почти весь урожай был уничтожен долгоносиками. С обычными вредителями крестьяне справляются самостоятельно, но данные особи были размером с целую корову! Возможно пострадал не только урожай, но выяснять этого никто не хочет. Разберитесь с проблемой, Искатели!"

[[event.locales]]
language = "EN"
intro = "Our harvest was devoured by a weevil!"
description = "A sudden attack struck the villages south of Krezar: almost the entire crop was destroyed by weevils. The peasants cope with the usual pests on their own, but these individuals were the size of a whole cow! Perhaps not only the harvest suffered, but no one wants to find out. Sort out the problem, Seekers!"

[[event]]
id = 16
duration = "PT30M"
isEnabled = true

[event.raid]
template = "ENEMY_GROUP"
name = "Гоблины"

[[event.locales]]
language = "RU"
intro = "Охота на гоблинов"
description = """
Срочно требуются искатели, чтобы помочь защитить окраины Крезара от растущей угрозы со стороны гоблинов. Эти твари уже не раз совершали набеги на близлежащие фермы, крали домашний скот и сеяли хаос в округе.
Недавно разведчики одной из гильдий обнаружили новое поселение к западу от города. Уничтожьте их, пока они не расплодились достаточно сильно и не стали серьёзной угрозой для местных."""

[[event.locales]]
language = "EN"
intro = "Goblin Hunting"
description = """
Seekers are urgently needed to help protect the outskirts of Krezar from the growing threat from goblins. These creatures have repeatedly raided nearby farms, stole livestock and wreaked havoc in the area.
Recently, scouts from one of the guilds discovered a new settlement to the west of the city. Destroy them before they breed strongly enough and become a serious threat to the locals."""

[[event]]
id = 17
duration = "PT30M"
isEnabled = true

[event.raid]
template = "ENEMY_GROUP"
name = "Крабий рейв"

[[event.locales]]
language = "RU"
intro = "Опасность на пляже"
description = "Крестьяне сообщают, что не могут пройти к своим лодкам и отправиться за рыбой в море. Гигантские крабы решили устроить дикий рейв прямо на пляже! Собираем группу Искателей, которые помогут жителям вернуться к работе. В случае успеха каждому участнику крабовый салат за счёт заведения!"

[[event.locales]]
language = "EN"
intro = "Danger on the beach"
description = "Peasants report that they can't walk to their boats and go to the sea for fish. Giant crabs have decided to have a wild rave right on the beach! Assemble a group of Seekers to help the residents get back to work. If successful, each participant gets a crab salad on the house!"
