[[raid]]
code = "dragon"
isEnabled = true

[raid.locales.RU]
intro = """\
Это птица? Это огненный шар? Это дракон! ДРАКОН???????

Этих тварей истребили ещё до появления Империи на карте мира. Не знаем откуда он взялся \
в окрестностях Крезара, однако необходимо срочно уничтожить его, пока он не начал нападать \
на мирное население."""

[raid.info]

# две передние лапы дракона
[[raid.info.personageTemplates]]
    count = 2
    [raid.info.personageTemplates.personage]
    health = 60000
    critChance = 15
    dodgeChance = 15
    critMultiplier = 1
    speed = 400
    baseThreat = 15
    position = "FRONT"

    [[raid.info.personageTemplates.personage.skills]]
    activeEnum = "BLEEDING"
    rank = "FIFTH"

    [[raid.info.personageTemplates.personage.attacks]]
    attackType = "SLASH"
    range = 1
    attack = 300

    [[raid.info.personageTemplates.personage.defenses]]
    defenseType = "LEATHER"
    defense = 400

# две задние лапы дракона
[[raid.info.personageTemplates]]
    count = 2
    [raid.info.personageTemplates.personage]
    health = 60000
    critChance = 15
    dodgeChance = 15
    critMultiplier = 1
    speed = 400
    baseThreat = 15
    position = "BACK"

    [[raid.info.personageTemplates.personage.skills]]
    activeEnum = "BLEEDING"
    rank = "FIFTH"

    [[raid.info.personageTemplates.personage.attacks]]
    attackType = "SLASH"
    range = 3
    attack = 300

    [[raid.info.personageTemplates.personage.defenses]]
    defenseType = "LEATHER"
    defense = 400

# голова дракона
[[raid.info.personageTemplates]]
    count = 1
    [raid.info.personageTemplates.personage]
    health = 80000
    critChance = 25
    dodgeChance = 25
    critMultiplier = 2
    speed = 350
    baseThreat = 5
    position = "FRONT"

    [[raid.info.personageTemplates.personage.skills]]
    activeEnum = "PRECISE_STRIKE"
    rank = "FIFTH"
    [[raid.info.personageTemplates.personage.skills]]
    activeEnum = "COUNTER_ATTACK"
    rank = "FIFTH"
    [[raid.info.personageTemplates.personage.skills]]
    activeEnum = "THORNS"
    rank = "FIFTH"

    [[raid.info.personageTemplates.personage.attacks]]
    attackType = "SLASH"
    range = 1
    attack = 200
    [[raid.info.personageTemplates.personage.attacks]]
    attackType = "MAGICAL"
    range = 2
    attack = 100

    [[raid.info.personageTemplates.personage.defenses]]
    defenseType = "ARCANE"
    defense = 400
    [[raid.info.personageTemplates.personage.defenses]]
    defenseType = "LEATHER"
    defense = 400

# живот дракона
[[raid.info.personageTemplates]]
    count = 1
    [raid.info.personageTemplates.personage]
    health = 200000
    critChance = 5
    dodgeChance = 5
    critMultiplier = 0.1
    speed = 150
    baseThreat = 40
    position = "MID"

    [[raid.info.personageTemplates.personage.skills]]
    activeEnum = "THORNS"
    rank = "FIFTH"
    [[raid.info.personageTemplates.personage.skills]]
    activeEnum = "SELF_HEAL"
    rank = "FIFTH"

    [[raid.info.personageTemplates.personage.attacks]]
    attackType = "BLUNT"
    range = 2
    attack = 500

    [[raid.info.personageTemplates.personage.defenses]]
    defenseType = "LEATHER"
    defense = 1000

# крылья дракона
[[raid.info.personageTemplates]]
    count = 2
    [raid.info.personageTemplates.personage]
    health = 70000
    critChance = 20
    dodgeChance = 5
    critMultiplier = 2
    speed = 300
    baseThreat = 40
    position = "MID"

    [[raid.info.personageTemplates.personage.skills]]
    activeEnum = "THORNS"
    rank = "FIFTH"
    [[raid.info.personageTemplates.personage.skills]]
    activeEnum = "HIT_AND_RUN"
    rank = "FIFTH"
    [[raid.info.personageTemplates.personage.skills]]
    activeEnum = "KNOCKBACK"
    rank = "FIFTH"

    [[raid.info.personageTemplates.personage.attacks]]
    attackType = "BLUNT"
    range = 2
    attack = 400

    [[raid.info.personageTemplates.personage.defenses]]
    defenseType = "LEATHER"
    defense = 600

# хвост дракона
[[raid.info.personageTemplates]]
    count = 1
    [raid.info.personageTemplates.personage]
    health = 70000
    critChance = 20
    dodgeChance = 20
    critMultiplier = 1.5
    speed = 500
    baseThreat = 20
    position = "BACK"

    [[raid.info.personageTemplates.personage.skills]]
    activeEnum = "BERSERK"
    rank = "FIFTH"
    [[raid.info.personageTemplates.personage.skills]]
    activeEnum = "KNOCKBACK"
    rank = "FIFTH"

    [[raid.info.personageTemplates.personage.attacks]]
    attackType = "PIERCE"
    range = 4
    attack = 500

    [[raid.info.personageTemplates.personage.defenses]]
    defenseType = "LEATHER"
    defense = 200
