[[raid]]
code = "ashen_wolves"
isEnabled = true

[raid.locales.RU]
intro = """\
Стая пепельных волков вышла из горных пещер и уже уничтожает обозы на северной дороге.
Нужно быстро собрать отряд и остановить их, пока хищники не добрались до поселений."""

[raid.info]

[[raid.info.personageTemplates]]
count = 1
[raid.info.personageTemplates.personage]
health = 650
critChance = 3
dodgeChance = 1
critMultiplier = 0.05
speed = 45
baseThreat = 22
position = "FRONT"

[[raid.info.personageTemplates.personage.skills]]
activeEnum = "BLEEDING"
rank = "SECOND"

[[raid.info.personageTemplates.personage.skills]]
activeEnum = "COUNTER_ATTACK"
rank = "FIRST"

[[raid.info.personageTemplates.personage.attacks]]
attackType = "SLASH"
range = 1
attack = 420

[[raid.info.personageTemplates.personage.defenses]]
defenseType = "PLATE"
defense = 60

[[raid]]
code = "dragon"
isEnabled = true

[raid.locales.RU]
intro = """\
Это птица? Это огненный шар? Это дракон! ДРАКОН???????

Этих тварей истребили ещё до появления Империи на карте мира. Не знаем откуда он взялся \
в окрестностях Крезара, однако необходимо срочно уничтожить его, пока он не начал нападать \
на мирное население."""

[raid.locales.ES]
intro = """\
¿Es un pájaro? ¿Es una bola de fuego? ¡Es un dragón! ¡¿UN DRAGÓN???????

Estas criaturas fueron exterminadas antes incluso de que el Imperio apareciera en el mapa del mundo. \
No sabemos de dónde ha salido en las cercanías de Krezar, pero hay que eliminarlo urgentemente \
antes de que empiece a atacar a la población pacífica."""

[raid.info]

[[raid.info.personageTemplates]]
count = 1
[raid.info.personageTemplates.personage]
health = 180000
critChance = 8
dodgeChance = 3
critMultiplier = 0.35
speed = 18
baseThreat = 12
position = "BACK"

[[raid.info.personageTemplates.personage.skills]]
activeEnum = "BERSERK"
rank = "THIRD"

[[raid.info.personageTemplates.personage.attacks]]
attackType = "MAGICAL"
range = 2
attack = 100

[[raid.info.personageTemplates.personage.defenses]]
defenseType = "PLATE"
defense = 300

[[raid]]
code = "swamp-thing"
isEnabled = true

[raid.locales.RU]
intro = """\
Обнаружена мерзкая болотная тварь!

Похоже на мутировавшую слизь. Умом и сообразительностью не отличается, зато очень даже отличается \
агрессивностью и живучестью. Несколько крестьян уже успели стать её жертвами, пока ходили в лес за грибами. \
Убейте её, пока жертв не стало больше."""

[raid.locales.ES]
intro = """\
¡Se ha detectado una asquerosa criatura del pantano!

Parece una baba mutada. No se destaca por su inteligencia o astucia, pero sí por ser increíblemente \
agresiva y resistente. Ya varios campesinos han caído víctimas suyas mientras recogían hongos en el bosque. \
Mátenla antes de que haya más víctimas."""

[raid.info]

[[raid.info.personageTemplates]]
count = 1
[raid.info.personageTemplates.personage]
health = 220000
critChance = 2
dodgeChance = 1
critMultiplier = 0.1
speed = 12
baseThreat = 15
position = "FRONT"

[[raid.info.personageTemplates.personage.skills]]
activeEnum = "THORNS"
rank = "THIRD"

[[raid.info.personageTemplates.personage.attacks]]
attackType = "BLUNT"
range = 1
attack = 80

[[raid.info.personageTemplates.personage.defenses]]
defenseType = "PLATE"
defense = 400
