spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost:5432}/${DATABASE_NAME:seeker}?prepareThreshold=0
spring.datasource.username=${DATABASE_USER:dev}
spring.datasource.password=${DATABASE_PASSWORD:dev}

server.port=${SERVER_PORT:8080}
