homyakin.seeker.telegram.local-bot-enabled=true
homyakin.seeker.telegram.local-bot-host=${LOCAL_BOT_HOST:localhost}
homyakin.seeker.telegram.local-bot-port=${LOCAL_BOT_PORT:8081}
homyakin.seeker.telegram.local-bot-schema=${LOCAL_BOT_SCHEMA:http}
