# TODO características
itemName = "${modifier}${object}"
fullItem = """\
${slots}${rarity_icon}${broken_icon}${item} ${optional_command}
${characteristics}"""
shortItem = "${slots}${rarity_icon}${broken_icon}${attack_type_icon}${defense_type_icon} ${item} ${optional_command} ${characteristics}"
characteristics = "${not_zero_health}${not_zero_attack}${not_zero_defense}${not_zero_range}${not_zero_speed}${not_zero_crit_chance}${not_zero_dodge_chance}${not_zero_crit_multiplier}${not_zero_threat}"
attack = "${attack_type_icon}${attack_value} "
defense = "${defense_type_icon}${defense_value} "
health = "${health_icon}${health_value} "
range = "${range_icon}${range_value} "
speed = "${speed_icon}${speed_value} "
critChance = "${crit_attack_icon}${crit_chance_value} "
dodgeChance = "${dodge_icon}${dodge_chance_value} "
critMultiplier = "${crit_multiplier_icon}${crit_multiplier_value} "
threat = "${threat_icon}${threat_value} "
personageFreeSlot = "${slot} <i>Vacío</i>"

equipment = """\
<b>👤Equipo:</b>
${equipped_items_and_free_slots}

⚔️Estadísticas de combate: ${battle_stats_command}"""

bag = """\
<b>🎒Mochila (${items_in_bag_count}/${max_items_in_bag}):</b>
${items_in_bag}"""

compactInventory = """\
<b>👤Equipo:</b>
${equipped_items_and_free_slots}

<b>🎒Mochila (${items_in_bag_count}/${max_items_in_bag}):</b>
${items_in_bag}

⚔️Estadísticas de combate: ${battle_stats_command}"""

equipmentButton = "👤Equipo"
bagButton = "🎒Mochila"

personageMissingItem = "No tienes ese objeto"
alreadyEquipped = "Ya tienes ese objeto equipado"
alreadyTakenOff = "Ese objeto no está equipado"
notEnoughSpaceInBag = "No tienes espacio en la mochila para quitar ese objeto"
notEnoughSpaceOnPutOnItem = "No tienes espacio en la mochila para quitar los objetos equipados: ${slots}"
successPutOn = "¡Equipado exitosamente!: ${item}"
successPutOnWithTakenOff = """\
Desequipado:
${taken_off_items}

¡Equipado exitosamente!: ${item}"""
successTakeOff = "Exitosamente desequipado: ${item}"
