duelMustContainsMention = """\
    Дуэльге қарсыласты таңдаңыз! Дуэль басқа пайдаланушының хабарламасына жауап жазып \
    немесе хабарламада оны атап өтіңіз, мысалы: <code>${duel_command} @user</code>.
    """
duelWithDifferentBot = [
    "Қарсылас ретінде жаны бар біреуді таңдаңыз!"
]
duelWithThisBot = [
    "Мен сізге қызметкерлермен ұрыспауды ұсынамын! Әйтпесе, сіздің сыраңыз даяшыдан арнайы көбікпен аяқталуы мүмкін."
]
duelWithYourself = "Сіз өз-өзіңізбен дуэль жасай алмайсыз!"
duelWithInitiatorNotEnoughMoney = [
    "Тоқтай тұрыныз! Аренаны пайдалану үшін сізге кем дегенде ${money_icon}${money_count} қажет. Алдымен барып, жұмыс істеңіз",
    "Аренаға кіру құны ${money_icon}${money_count}, біріншіден, жұмыс істеп кел!",
    "Жекпе-жек - кедейлердің емес, байлардың артықшылығы. ${money_icon}${money_count} тапсан қана кайтып кел.",
    "Бұл жекпе-жекті көтере алмайтын сияқтысың! ${money_icon}${money_count} табуың керек."
]
personageAlreadyStartDuel = "Сіз басқа дуэльді бастадыңыз! Оның аяқталуын күтіңіз."
notDuelAcceptingPersonage = "Дуэльге сізді шақырған жоқ!"
expiredDuel = [
    "Дуэльге шақыру еленбеді",
    "${mention_acceptor_icon_with_name}: Мен дуэльге барғым келеді ме, келмейді ме, маған бәрібір!",
    "${mention_acceptor_icon_with_name} дуэльге шыға алмайды. Кейінірек қоңырау шалыңыз.",
]
declinedDuel = [
    "Қабылдаушы тарап шақыруды қабылдамады!",
    "Ха! ${mention_initiator_icon_with_name}, дуэльге шақыруға ақымақты басқа жерден ізде!"
]
finishedDuel = [
    """\
Іздеуші ${mention_winner_icon_with_name} жеңіп \
${mention_loser_icon_with_name}-нің тас-талқанын шығарды""",
    "${mention_loser_icon_with_name} жеңіліске ұшырады",
]
finishedDuelResult = """\
${finished_duel}

${time_icon}Раундтар: ${rounds_count}
${winner_result}
${loser_result}"""
acceptDuelButton = "Қабыл алу🗡"
declineDuelButton = "Бас тарту👐"
duelWithUnknownUser = [
    """\
Өкінішке орай, қызметкерлер жекпе-жекке кімді шақырғаныңызды білмейді.\
Мүмкін сіздің досыңыз бұл тавернаға әлі келмеген немесе ол атын өзгерткен шығар."""
]
duelIsLocked = "Дуэль өңделуде, кейінірек қайталап көріңіз."
duelAlreadyFinished = "Дуэль ертерек аяқталды, бірақ жүйелік қатеге байланысты нәтиже көрсетілмеді. Кешірім сұраймыз."
