[menu]
profileButton = "👤Профиль"
languageButton = "🌐Тіл"
receptionDeskButton = "✍️Қабылдау"
backButton = "⬅️Артқа"
changeNameButton = "🔮Атымды өзгерту"

[changeName]
changeNameWithoutName="Атыңыз бос болмауы керек!"
cancelChangeName = "Сиқырлы шеңбер өшіп бара жатыр. Келесі жолы..."
confirmName = "Сіздің жаңа атыңыз: <code>${name}</code>. Дұрыс па?"
personageNameInvalidLength = """\
Кешіріңіз, бірақ сиқырлы шеңбердің атауында таңбалар шегі бар. ${min_name_length} - ${max_name_length} таңба"""
personageNameInvalidSymbols = """\
Өкінішке орай, сиқырлы шеңберде атыңызды сақтау ушін сіз тек мыналарды пайдалана аласыз: \
<code>Кирилл, латын, сандар, таңбалар _-.#№ және пробел</code>"""
successNameChange = "Атыңыз сәтті өзгертілді! Сиқырлы шеңбер өшіп бара жатыр."
internalError = "Сиқырлы шеңбер жыпылықтай бастап, кенеттен сөніп қалды. Бір жерде қате шыққан сияқты, әрекетті кейінірек қайталаңыз."
cancelButton = "❌Бас тарту"
confirmButton = "✅Барлығы дұрыс"
repeatButton = "🔄Тағы бір рет"

[settings]
personageIsHidden = "Сіз жаһандық рейтингтер мен статистикадан жасырылдыңыз."
personageIsUnhidden = "Жетістіктеріңіз қайтадан барлық іздеушілерге көрінеді."
settings = """\
⚙️Баптаулар:

Хабарландырулар — фондық оқиғалар туралы хабарламалар: энергияны қалпына келтіру, квесттер және т.б.
Автоматты квесттер — энергия толық болғанда автоматты түрде квестке жіберу. Бұл көбірек энергия жұмсайды.
Ықшам заттар — заттардың ықшам көрінісі."""
sendNotificationsButton = "${enabled_icon}Хабарландырулар"
autoQuestingButton = "${enabled_icon}Автоматты квесттер"
compactItemsButton = "${enabled_icon}Ықшам заттар"
