chooseLanguage = "Тілді таңдаңыз:"
onlyAdminAction = "Бұл әрекет тек администраторларға ғана қолжетімді"
internalError = "Қате, кейінірек қайталап көріңіз"

hoursShort = "сағ."
minutesShort = "мин."
daysShort = "күн"
durationJustNow = "қазір"

# текста для лички
receptionDesk = "Сәлеметсіз бе! Көмегім қажет пе?"

contrabandEffect = "\n<code>-📦Контрабанда: ${effect} ${time_icon}${duration}</code>"
