[activeTime]
incorrectArgumentsNumber = "Пробелмен бөлінген үш аргумент жазуыңыз керек.: [басталатын_уақыты] [аяқталатын_уақыты] [уақыт_белдеуі]"
argumentsNotANumber = "Барлық аргументтер бүтін сандар болуы керек"
successChange = " !"
incorrectHour = "Уақыт дұрыс емес, ол 0 мен 24 арасындағы бүтін сан болуы керек."
startMoreThanEnd = "Қате! Басталу уақыты аяқталу уақытынан кейін жазылған"
incorrectTimeZone = "Уақыт белдеуі дұрыс жазылмаған, ол ${min_time_zone} және ${max_time_zone} аралығындағы бүтін сан болуы керек"
current = "Группаның қазіргі ойнайтын уақыттары: <code>${active_time}</code>"
