main = """\
Крезар қаласының тавернасына қош келдіңіз!

Мұнда сіз демала аласыз, сусын іше аласыз немесе біреуді дуэльге шақырып өзіңіздің күшіңізді көрсете аласыз. \
Сондай-ақ рейдтерден біраз алтын табуға болады.

Көмек сұраудан тартынбаңыз, біз сізге көмектесуге қуаныштымыз.
"""

raids = """\
Рейдтерге қатысу үшін ботты группаңызға қосуыңыз керек.
Содан кейін, белгілі бір уақыт аралығында тавернада хабарландырулар пайда болады. \
Рейдтерге қатысып біраз алтын табуға болады. Егер рейд сәтті болса, сыйақы артады.

Және де есіңізде болсын! Неғұрлым көп іздеушілер болса, ұту мүмкіндігі соғұрлым жоғары болады!

Рейдке қатысқан сайын ${energy_icon}Энергияңыз нөлге дейін төмендейді, одан кейін автоматты түрде қалпына келеді. \
Энергия сіздің шайқастағы тиімділігіңізге және сіз алатын сыйақыға әсер етеді.

Тобыңыздың ұйқы кезінде хабарландырулар алуын қаламасаңыз, гильдияға ойнай алатын бос уақытыңызды \
${set_active_time_command} [басталатын_уақыты] [аяқталатын_уақыты] [уақыт_белдеуі] арқылы айта аласыз. \
Мысалы: <code>${set_active_time_command} 6 24 +3</code>.
"""

duels = """\
Біреумен күш салыстырғыларың келсе, тавернаның артында төбелеске арналған арнайы арена бар!
${duel_command} арқылы қарсыласыңның хабарына жауап беріңіз.

Дегенмен, арена тегін ләззат емес екенін біліңіз! Біреу оны қаннан жуып, құлаған тістерді алуы керек.
"""

menu = """\
Кез келген өзін-өзі құрметтейтін таверна сияқты, мұнда дәмді тағамдарды ішіп, жеуге болады.

${menu_command} арқылы қолжетімді заттардың тізімін қарап шығыңыз және өзіңізге ұнайтын нәрсеге тапсырыс беріңіз!
Және де сіз досыңызды тамақтандыра аласыз: досыңыздың хабарламасына жауап жазып \
немесе хабарламада оны атап өтіңіз: <code>${order_command}1 @user</code>.
"""

personage = """\
${bot_username} өту арқылы қабылдау бөлімін пайдалана аласыз.

Онда сіз сиқырлы шеңберді пайдаланып атыңызды өзгерте аласыз.
Немесе сіз «Ұмыту кітабына» қол жеткізу үшін төлеп, өзіңіздің жауынгерлік дағдыларыңызды ұмытып, жаңаларын үйрене аласыз.
"""

info = """\
Проект жаңалықтарын мына арнадан көруге болады: ${news_channel_username}.

Ойынның исходный кодын <a href="${source_code_link}">осы жерден</a> таба аласыз.
Сондай-ақ осы сілтеме арқылы контентті басқа тілдерге аударып қалай көмектесуге болатынын таба аласыз.
"""


raidsButton = "🗡Рейдтер"
duelsButton = "🤺Дуэльдер"
menuButton = "🍻Таверна"
personageButton = "🔰Іздеуші"
infoButton = "💬Басқа"

