main = """\
Крезар қаласының тавернасына қош келдіңіз!

Мұнда сіз демала аласыз, сусын іше аласыз немесе біреуді дуэльге шақырып өзіңіздің күшіңізді көрсете аласыз. \
Сондай-ақ рейдтерден біраз алтын табуға болады.

Көмек сұраудан тартынбаңыз, біз сізге көмектесуге қуаныштымыз.
"""

duels = """\
Біреумен күш салыстырғыларың келсе, тавернаның артында төбелеске арналған арнайы арена бар!
${duel_command} арқылы қарсыласыңның хабарына жауап беріңіз.

Дегенмен, арена тегін ләззат емес екенін біліңіз! Біреу оны қаннан жуып, құлаған тістерді алуы керек.
"""

personage = """\
${bot_username} өту арқылы қабылдау бөлімін пайдалана аласыз.

Онда сіз сиқырлы шеңберді пайдаланып атыңызды өзгерте аласыз.
"""

info = """\
Проект жаңалықтарын мына арнадан көруге болады: ${news_channel_username}.

Ойынның исходный кодын <a href="${source_code_link}">осы жерден</a> таба аласыз.
Сондай-ақ осы сілтеме арқылы контентті басқа тілдерге аударып қалай көмектесуге болатынын таба аласыз.
"""


raidsButton = "🗡Рейдтер"
duelsButton = "🤺Дуэльдер"
menuButton = "🍻Таверна"
personageButton = "🔰Іздеуші"
infoButton = "💬Басқа"

