joinRaidEvent = "Рейдке қосылу🗡 ${energy_icon}${energy_cost}%"
userAlreadyInOtherEvent = "❌Сіз басқа шараға қатысып жатырсыз!"
expiredRaid = "❌Рейд аяқталды!"
raidNotFound = "⚠️Рейд табылмады!"
raidInProcess = "❌Рейд басталып кетті"
successRaid = [
    "Шара аяқталды! Рейд сәтті өтті.",
    "Бұл эпикалық шайқас болды! Сіз жетістікке жеттіңіз, міне, сіздің сыйлығыңыз!",
    "Қарсыластар жеңілді! Ал сіз боқ мұрын емес екенсіз!"
]
failureRaid = [
    "Іздеушілер рейдте сәтсіздікке ұшырады. Біз сізге ақшаны не үшін төлеп жатырмыз?",
    "Эх, сәтсіздік. Мүмкін көбірек іздеушілерді жинау керек шығар?"
]
zeroParticipants = [
    "Тапсырысты ешкім қабылдамады😢Бұл жолы ақшаны ешкім алмайды."
]
successContrabandForPersonage = [
    "${personage_badge_with_name} өрісте <b>${contraband_name}</b> табады! Ішінде бірдеңе шыңғырайды...📦"
]
