menuHeader = "Бүгін мәзірде:"
drinks = "Сусындар"
mainDishes = "Тағамдар"
itemNotInMenu = "Бұл тармақ мәзірде жоқ!"
notEnoughMoneyDrink = [
    "Сізге ${money_icon}${not_enough_money_value} жетпейді, жұмысқа барыңыз, содан кейін ішіңіз!",
    "Бұл сусын сізге арналмағаны анық! Оның құны ${money_icon}${item_cost}"
]
notEnoughMoneyMainDish = [
    "Жұмыс істемейтін адам тамақ ішпейді! Қосымша ${money_icon}${not_enough_money_value} табыңыз"
]
orderGiftToDifferentBot = [
    "Кешіріңіз, бірақ жансыз заттарға тапсырыс қабылданбайды."
]
orderGiftToThisBot = [
    "Барменге құймаңыз"
]
order = [
    "${mention_acceptor_icon_with_name} үшін ${item_name}!"
]
orderGift = [
    "Тапсырыс! ${item_name} ${mention_giver_icon_with_name} -нан ${mention_acceptor_icon_with_name} -ға"
]
expiredOrder = [
    "Тапсырыстың бос тұрғаны сонша, оны аш даяшы жеп қойған. Өкінішке орай, ол ақша қалдырған жоқ."
]
consumeDrinkButton = "🍺Ішу"
consumeMainDishButton = "🍽Жеу"
consumeAlreadyInFinalStatus = "Тапсырыс жоғалып кетті... Мыстан кемпір алып кеткен шығар"
wrongConsumer = "Ол сенің тапсырысың емес!"
orderToUnknownUser = [
    """\
Даяшылар бұл Іздеушіні клиенттердің арасынан таппады. \
Мүмкін сіздің досыңыз бұл тавернаға әлі келмеген немесе ол атын өзгерткен шығар."""
]
orderIsLocked = "Тапсырысыңыз өңделуде, кейінірек қайталаңыз."
