registeredGroupInfo = """\
<code>${group_name_with_badge}</code>

Участники: ${members_count}

📊Статистика группы: ${group_stats_command}
⚙️Настройки: ${group_settings_command}
Комманды для группы: ${group_commands_command}
"""
unregisteredGroupInfo = """\
<code>${group_name_with_badge}</code>

Зарегистрировать группу: ${register_group_command}

📊Статистика группы: ${group_stats_command}
⚙️Настройки: ${group_settings_command}
"""

groupRegistration = """\
Для регистрации группы необходимо установить тэг группы <code>${register_group_command} тэг</code>. \
Тэг должен стостоять из 3-4 заглавных букв латинского алфавита."""
alreadyRegisteredGroup = "Группа уже зарегистрирована"
registrationPersonageInAnotherGroup = "Регистрирующий персонаж не должен быть участником другой группы!"
incorrectTag = "Неправильно указан тэг, он должен состоять из 3-4 заглавных букв латинского алфавита"
tagAlreadyTaken = "Такой тэг уже занят"
successGroupRegistration = "Группа успешно зарегистрирована! Вступить в группу можно с помощью ${group_join_command}"
successChangeTag = "Тэг успешно изменён на <code>[${tag}]</code>"

joinPersonageAlreadyInGroup = "Ты уже состоишь в этой группе!"
joinPersonageInAnotherGroup = "Ты уже состоишь в другой группе!"
joinPersonageTimeout = "Ты не можешь вступить в группу в течениe ${duration}"
groupNotRegisteredAtJoin = "Группа должна быть зарегистрирована для вступления: ${register_group_command}"
successJoinGroup = "<code>${personage_badge_with_name}</code> теперь состоит в группе <code>${group_name_with_badge}</code>!"
joinPersonageConfirmationRequired = """\
Для вступления <code>${personage_badge_with_name}</code> в группу необходимо подтверждение администратора"""
joinGroupConfirmButton = "✅Подтвердить"
joinGroupCancelButton = "❌Отказать"
joinPersonageConfirmed = """\
Разрешение на вступление для <code>${personage_badge_with_name}</code> в группу получено \
от <code>${admin_badge_with_name}</code>"""
joinPersonageCanceled = "Вступление в группу <code>${personage_badge_with_name}</code> отменено"
joinConfirmNotMember = "Для подтверждения надо состоять в группе"

leaveGroupSuccess = "<code>${personage_badge_with_name}</code> больше не состоит в группе. Вступление заблокировано на ${duration}"
leaveGroupNotMember = "Ты не состоишь в этой группе"
leaveGroupNotAnyMember = "Ты не состоишь ни в какой группе"
leaveGroupLastMemberConfirmation = "После тебя в группе не будет участников, и она будет снята с регистрации"
leaveGroupConfirmButton = "✅Покинуть"
leaveGroupCancelButton = "❌Отменить"
leaveGroupLastMemberSuccess = """
<code>${personage_badge_with_name}</code> больше не состоит в группе. \
<code>${group_name_with_badge}</code> снята с регистрации.
Вступление заблокировано на ${duration}"""
leaveGroupCancel = "Ты остаёшься в группе"

groupCommands = """\
Комманды для группы:
<code>${group_join_command}</code> - вступить в группу
<code>${group_leave_command}</code> - покинуть группу
<code>${change_tag_command} [тэг]</code> - сменить тэг группы"""
