outpost = """
🏰<b>Аванпост</b>

${slots}
"""
emptySlot = "<i>[Пустой слот]</i>"
buildingSlot = "${building_name} — ур. ${level}"

monolith = "Монолит"

openInPrivateButton = "🧱На стройку"
outpostNoGroup = "Сначала вступи в группу, чтобы пользоваться аванпостом."

startBuildingButton = "🏗 Начать строительство"
chooseBuildingTitle = "<b>Выбери здание</b>"
confirmNewBuilding = "Построить <b>${building_name}</b> (ур. ${to})?"
confirmUpgradeBuilding = "Повысить <b>${building_name}</b> с ур. ${from} до ${to}?"
buildingButtonLabel = "${building_name} ${from} -> ${to}"
confirmStartButton = "✅ Построить"
confirmUpgradeButton = "✅ Улучшить"
cancelStartButton = "❌ Отмена"
startBuildingSuccessPrivate = "Строительство начато."
startBuildingCanceled = "Строительство отменено."
groupBuildingStarted = "🏗 В аванпосте начато строительство: <code>${building_name}</code> (${from} → ${to}).\nИнициатор: ${initiator}"
notAdminOutpost = "Только администратор группы может начинать строительство."
startBuildingConflict = "Нельзя построить это здание."
