[menu]
profileButton = "👤Профиль"
languageButton = "🌐Язык"
receptionDeskButton = "✍️Стойка регистрации"
backButton = "⬅️Назад"
resetCharacteristicsButton = "📖Книга забвения"
changeNameButton = "🔮Сменить имя"
showBadgesButton = "🔰Жетоны"
inventoryButton = "🎒Инвентарь"

[changeName]
changeNameWithoutName="Имя не может быть пустым!"
initChangeName = """
Магический круг светится от потока магии. Необходимо написать имя, под которым тебя будут знать другие Искатели.
Разрешённые символы: <code>кириллица, латиница, цифры, _-.#№ и пробел</code>
"""
cancelChangeName = "Магический круг затухает. В другой раз..."
confirmName = "Твоё новое имя: <code>${name}</code>. Правильно?"
personageNameInvalidLength = """\
Прости, но в магическом круге есть ограничение на символы в имени. От ${min_name_length} до ${max_name_length} символов"""
personageNameInvalidSymbols = """\
К сожалению, в магическом круге для сохранения имени можно использовать только: \
<code>кириллицу, латиницу, цифры, символы _-.#№ и пробел</code>"""
successNameChange = "Имя успешно изменено! Магический круг затухает."
internalError = "Магический круг начинает мерцать и резко затухает. Похоже произошла ошибка, попробуйте позже."
cancelButton = "❌Отказаться"
confirmButton = "✅Всё верно"
repeatButton = "🔄Ещё раз"

[characteristics]
resetConfirmation = """\
Для того, чтобы прочесть книгу забвения необходимо заплатить ${money_icon}${money_count}. \
Ты точно хочешь забыть свои старые навыки?"""
successReset = """\
После прочтения книги сознание затуманивается... Ты забываешь свои старые навыки. Перед тобой снова открыты все пути."""
canceledReset = "Книга останется здесь. Приходи, когда решишься"
increasedCharacteristic = "Ты улучшил навык: ${increased_value}${increased_icon}."
currentCharacteristics = """\
Текущие характеристики: ${strength_value}${strength_icon}${agility_value}${agility_icon}${wisdom_value}${wisdom_icon}"""
chooseCharacteristic = """\
Выбери, что ты хочешь изучить:
(${strength_icon}>${agility_icon}>${wisdom_icon}>${strength_icon})"""
notEnoughCharacteristicPoints = "Ты достиг своего предела! Если захочешь изменить стиль боя, воспользуйся книгой забвения."
notEnoughMoney = "Книга забвения тебе не по карману! Нужно ${money_icon}${money_count}"
profileLevelUp = "Ты можешь улучшить свои навыки! Жми ${level_up_command}"
confirmButton = "📖Прочесть"
cancelButton = "❌В другой раз"
strengthButton = "+1${strength_icon}"
agilityButton = "+1${agility_icon}"
wisdomButton = "+1${wisdom_icon}"

[badges]
availableBadges = """\
Доступные жетоны:

${badge_list}"""
badge = """\
${badge_icon} ${badge_description}"""
badgeIsNotAvailable = "Данный жетон недоступен"
