joinRaidEvent = "Вступить в рейд 🗡 ${energy_icon}${energy_cost}%"
userAlreadyInThisRaid = "✅Вы уже участвуете в этом рейде!"
userAlreadyInOtherEvent = "❌Вы уже участвуете в другом событии!"
exhaustedAlert = "⚠️Вы слишком устали! Вы сможете сразиться в рейде, но без награды. Энергия не потрачена."
expiredRaid = "❌Рейд завершён!"
raidNotFound = "⚠️Рейд не найден!"
raidInProcess = "❌Рейд уже начался"
successJoinRaid = "✅Вы успешно присоединились к рейду!"
successRaid = [
    "Событие завершилось! Рейд был успешен.",
    "Эпичный был бой! Вы преуспели, вот ваша награда!",
    "Противники повержены! А вы, оказывается, не сопляки!"
]
failureRaid = [
    "Искатели провалили рейд. За что мы вам деньги платим?",
    "Эх, провал. Может, стоит собрать больше искателей?",
    "Бой был не самым успешным. Теперь вы по уши в дерьме."
]
zeroParticipants = [
    "Никто не принял заказ😢 В этот раз денег никто не получит."
]
personageRaidResult = "${dead_icon_or_empty}${raid_participant}: ${damage_dealt}⚔️ ${damage_taken}🛡 +${money}${money_icon}"
raidResult = """\
${success_or_failure}

Противники: ${remain_enemies_health}/${total_enemies_health}❤️ ${remain_enemies_count}/${total_enemies_count}👹
Искатели: ${participants_health}/${participants_max_health}❤️ ${living_participants}/${total_participants}🔰

Лучшие:
${top_participants_list}${from_new_line_items_for_personages}

Отчёт о рейде: ${raid_report_command}"""
successItemForPersonage = [
    "${personage_badge_with_name} обнаруживает на поле <code>${short_item}</code>! Необходимо обмыть находку в таверне🍻"
]
successContrabandForPersonage = [
    "${personage_badge_with_name} нащупал в пыли после боя <b>${contraband_name}</b>! Что-то гремит внутри...",
    "${personage_badge_with_name} споткнулся о <b>${contraband_name}</b>! Замок выглядит подозрительно.",
    "${personage_badge_with_name} обнаруживает <b>${contraband_name}</b> среди обломков. От него несёт контрабандой."
]
notEnoughSpaceInBagForItem = [
    "${personage_badge_with_name} обнаруживает на поле <code>${short_item}</code>, но не может унести из-за полного рюкзака...😢"
]
raidParticipants = "Участники: ${raid_participants_list}"
raidParticipant = "${personage_badge_with_name}${exhausted_icon_or_empty}"
report = """\
📜Ваш отчёт за последний рейд:
${personage_battle_report}"""
reportNotPresentForPersonage = "Не смогли найти твой отчёт о рейде в архивах"
lastGroupRaidReportNotFound = "Ты не участвовал в последнем рейде"
raidBaseMessage = """\
<b>${raid_intro}</b>

Уровень рейда: ${raid_level}

${raid_description}

${raid_participants}"""

raidStarting = """\
${raid_base_message}

Битва начнётся через ${duration}"""
