menu = """\
📦Случайные коробки предметов:
${buying_items}

🎒Ваши предметы:
${selling_items}
"""

sellingItem = "${full_item} ${money_icon}${price_value} ${sell_command}"
buyingItem = "${shop_item_icon}${shop_item_name} ${money_icon}${price_value} ${buy_command}"

common = "Обычная"
uncommon = "Необычная"
rare = "Редкая"
epic = "Эпическая"
legendary = "Легендарная"
random = "Случайная"

incorrectBuyingItem = "В магазине нет такого предмета."
incorrectSellingItem = "У вас нет такого предмета."
notEnoughMoney = "Недостаточно денег."
notEnoughSpaceInBag = "В рюкзаке недостаточно места, чтобы купить предмет."
successBuy = "Поздравляем с покупкой! <code>${full_item_name}</code>"
successSell = "Продано! <code>${full_item_name}</code> +${money_icon}${price_value}"
