[menu]
profileButton = "👤Profile"
languageButton = "🌐Language"
receptionDeskButton = "✍️Reception Desk"
backButton = "⬅️Back"

[changeName]
changeNameWithoutName = "Enter the name separated by a space after the command: \"${name_command} Name\""
personageNameInvalidLength = """\
Sorry, but in the magic circle there is a restriction on the characters in the name. \
From ${min_name_length} to ${max_name_length} characters"""
personageNameInvalidSymbols = """
Unfortunately, in the magic circle to save the name, you can only use: \
cyrillic, latin, numbers characters _-.#№: and a space"""
successNameChange = "Name has been successfully changed!"

[settings]
personageIsHidden = "You are hidden from global rankings and statistics."
personageIsUnhidden = "Your achievements are visible to other Seekers again."
settings = """\
⚙️Settings:

Notifications — send alerts about background events: energy recovery, quests, etc.
Auto quests — automatically start a quest when energy is full. Uses more energy.
Compact items — compact item display."""
sendNotificationsButton = "${enabled_icon}Notifications"
autoQuestingButton = "${enabled_icon}Auto quests"
compactItemsButton = "${enabled_icon}Compact items"