joinRaidEvent = "Join raid🗡(${energy_icon}${energy_cost}%)"
userAlreadyInOtherEvent = "❌You are already participating in another event!"
expiredRaid = "❌This event is over!"
raidNotFound = "⚠️Raid not found!"
successRaid = [
    "Raid was successful."
]
failureRaid = [
    "The seekers failed the raid."
]
successContrabandForPersonage = [
    "${personage_badge_with_name} finds <b>${contraband_name}</b> on the field! Something rattles inside...📦"
]
