# Сам предмет, который описывают модификаторы выше
[[item]]
code = "sword"
type = "ONE_HANDED_SWORD"
attack.min = 1
attack.max = 1

[item.locales.RU]
text = "Меч"
form = "MASCULINE"

[item.locales.EN]
text = "Swrod"
form = "WITHOUT"

[[item]]
code = "club"
type = "ONE_HANDED_BLUNT"
attack.min = 1
attack.max = 1

[item.locales.RU]
text = "Палица"
form = "FEMININE"

[item.locales.EN]
text = "Club"
form = "WITHOUT"

[[item]]
code = "spear"
type = "POLE_WEAPON"
attack.min = 2
attack.max = 2

[item.locales.RU]
text = "Копьё"
form = "NEUTER"

[item.locales.EN]
text = "Spear"
form = "WITHOUT"
