# Сам предмет, который описывают модификаторы выше
[[object]]
code = "sword"
slots = ["MAIN_HAND"]
characteristics.attack = "1-1"

[object.locales.RU]
text = "Меч"
form = "MASCULINE"

[object.locales.EN]
text = "Swrod"
form = "WITHOUT"

[[object]]
code = "club"
slots = ["MAIN_HAND"]
characteristics.attack = "1-1"

[object.locales.RU]
text = "Палица"
form = "FEMININE"

[object.locales.EN]
text = "Club"
form = "WITHOUT"

[[object]]
code = "spear"
slots = ["MAIN_HAND", "OFF_HAND"]
characteristics.attack = "2-2"

[object.locales.RU]
text = "Копьё"
form = "NEUTER"

[object.locales.EN]
text = "Spear"
form = "WITHOUT"
