# Сам предмет, который описывают модификаторы выше
[[object]]
code = "sword"
type = "ONE_HANDED_SWORD"
attack = "1-1"

[object.locales.RU]
text = "Меч"
form = "MASCULINE"

[object.locales.EN]
text = "Swrod"
form = "WITHOUT"

[[object]]
code = "club"
type = "ONE_HANDED_BLUNT"
attack = "1-1"

[object.locales.RU]
text = "Палица"
form = "FEMININE"

[object.locales.EN]
text = "Club"
form = "WITHOUT"

[[object]]
code = "spear"
type = "POLE_WEAPON"
attack = "2-2"

[object.locales.RU]
text = "Копьё"
form = "NEUTER"

[object.locales.EN]
text = "Spear"
form = "WITHOUT"
