[[quest]]
    code = "cat-search"
    isEnabled = true

    [quest.locales.RU]
    intro = "Маленький Тимми потерял своего драгоценного котика. Ты же Искатель? Ну так ищи, чего встал?"
    success = """\
    Ты обыскал половину города: рылся в помойке, спускался в канализацию, исследовал бордели. \
    Но, в конце-концов, злосчастный котик был найден и доставлен счастливому владельцу. \
    Прекрасный повод, чтобы выпить!"""
    failure = """\
    Кота ты нашёл. Но это был не просто кот, а настоящий монстр. В неравной схватке ты потерпел сокрушительное \
    поражение. Вернулся в таверну весь в царапинах и с пустыми руками, время запить этот день."""

[[quest]]
    code = "gardening-help"
    isEnabled = true

    [quest.locales.RU]
    intro = "Любишь вкусно покушать в таверне? Люби и в огороде помочь! Лопату в зубы и вперёд, солнце ещё высоко!"
    success = """\
    Картошка выкопана, сорняки прополоты, кусты политы, огурцы собраны, коты поглажены, животные покормлены. \
    Хорошая работа, хорошая награда!"""
    failure = """\
    Пока занимался огородными делами, решил немного перекусить местными ягодами. Тебя обнаружили и \
    дали волшебных звиздюлей. Денег, кстати, не дали."""

[[quest]]
    code = "tavern-menu-help"
    isEnabled = true

    [quest.locales.RU]
    intro = "Повара разрабатывают новое меню для таверны! Нужны подопытные для дегустации, желательно без родственников."
    success = """\
    Потрясающий день: наелся, ещё и денег дали. Особенно ты отметил пюрешку с котлетками от нового повара."""
    failure = """\
    Очнулся где-то под забором. Кажется, ты пробовал слаймовое пиво... Или не пробовал... Какой сегодня день?"""

[[quest]]
    code = "forest-ingredients"
    isEnabled = true

    [quest.locales.RU]
    intro = "Алхимикам нужны ингредиенты из леса для зелий! Вот список, шуруй на поиски."
    success = """\
    Ты продуктивно провёл время на свежем воздухе и собрал всё необходимое в лесу. Хорошо постарался."""
    failure = """\
    Ты вляпался в дерьмо в лесу. Больше ничего интересного не произошло."""

[[quest]]
    code = "kindergarten"
    isEnabled = true

    [quest.locales.RU]
    intro = "Нужна временная сиделка для детей Искателей, которые находятся в рейде! Оплата почасовая."
    success = """\
    Дети вели себя послушно, никто не пострадал. Ты хорошо провёл время и даже немного отдохнул."""
    failure = """\
    Это ад во плоти! Дети кидались друг в друга едой, таскали друг друга за волосы, а тебя вообще \
    заперли в туалете. Благо ты успел убежать до того, как вернулись разгневанные родители."""

[[quest]]
    code = "tavern-waiter"
    isEnabled = true

    [quest.locales.RU]
    intro = "Подработка официантом в таверне! Прочувствуй адский труд персонала на своей шкуре и заработай немного денег."
    success = """\
Ты ловко управляешься с заказами: разносишь блюда, подливаешь напитки и даже успеваешь рассказать \
парочку бородатых анекдотов из своего арсенала. Владелец отсчитывает твои честно заработанные деньги."""
    failure = """\
Перепутаны почти все заказы, отпито пиво из общей бочки, съедена чужая картошечка. \
В конце дня вообще прилетел стакан в голову. Денег не дали, только сочувственно похлопали по спине."""

[[quest]]
    code = "rat-invasion"
    isEnabled = true

    [quest.locales.RU]
    intro = "В подвале таверны завелись крысы! И не простые, а магические, после той самой катастрофы. Нужен смельчак для зачистки."
    success = """\
    Оказалось, крысы были довольно разумными. Ты не только выгнал их из подвала, но и договорился, \
    что они будут присматривать за окрестностями таверны. Владелец таверны в восторге от такого креативного решения!"""
    failure = """\
    Крысы оказались не только магическими, но и организованными. Их предводитель провёл блестящую \
    тактическую операцию, и теперь ты платишь им дань сыром. Позорище."""

[[quest]]
    code = "magic-cleaning"
    isEnabled = true

    [quest.locales.RU]
    intro = "После вчерашней магической дуэли стены таверны покрылись странными узорами. Нужно отмыть, пока они не начали светиться!"
    success = """\
    С помощью щётки, мыла и капельки магии ты справился с заданием. Теперь стены таверны сияют \
    чистотой, а ты сияешь от гордости и звона монет в кармане."""
    failure = """\
    Ты только усугубил ситуацию. Узоры не только засветились, но и начали петь похабные песни. \
    Теперь придётся звать магистра для очистки. За твой счёт, разумеется."""

[[quest]]
    code = "lost-scroll"
    isEnabled = true

    [quest.locales.RU]
    intro = "Пьяный маг потерял важный свиток где-то в таверне. Обещает щедрое вознаграждение за находку!"
    success = """\
    Свиток нашёлся в самом неожиданном месте - в бочке с пивом. Хорошо, что ты догадался искать именно там. \
    Маг расплатился звонкой монетой, хоть и не помнит, как умудрился засунуть свиток в бочку."""
    failure = """\
    Ты нашёл свиток, но случайно активировал его. Теперь у тебя розовые волосы и хвост как у павлина. \
    Маг только посмеялся и отказался платить. Кажется, это была шутка с его стороны."""

[[quest]]
    code = "mushroom-hunt"
    isEnabled = true

    [quest.locales.RU]
    intro = "Повару нужны особые светящиеся грибы для нового блюда. Они растут только ночью в Зачарованном лесу!"
    success = """\
    Грибы найдены, собраны и доставлены. Бонусом ты узнал, что они умеют насвистывать весёлые мелодии. \
    Повар в восторге, ты при деньгах."""
    failure = """\
    Ты перепутал грибы и принёс какие-то сомнительные поганки. После их готовки вся посуда в таверне \
    начала танцевать джигу. Готовься к вычетам из зарплаты."""

[[quest]]
    code = "ghost-party"
    isEnabled = true

    [quest.locales.RU]
    intro = "В старой части таверны завелись призраки. И ладно бы просто завелись - они устраивают шумные вечеринки по ночам!"
    success = """\
    Ты не стал изгонять призраков, а договорился с ними о культурном досуге. Теперь они играют \
    тихую музыку и привлекают туристов. Владелец таверны очень доволен таким решением."""
    failure = """\
    Попытка изгнания призраков обернулась катастрофой. Теперь они не только шумят по ночам, \
    но и требуют включать их в меню таверны как почётных гостей."""

[[quest]]
    code = "magic-brew"
    isEnabled = true

    [quest.locales.RU]
    intro = "Нужен доброволец для тестирования нового сорта магического пива! Награда - бесплатная кружка и горсть монет."
    success = """\
    Пиво оказалось отменным! После дегустации ты мог летать и говорить с котами. \
    Эффект прошёл, а деньги остались - прекрасный день!"""
    failure = """\
    После первого же глотка ты начал икать мыльными пузырями и светиться в темноте. \
    Владелец таверны отказался платить, сказав что ты и так теперь работаешь ночным освещением."""

[[quest]]
    code = "bard-crisis"
    isEnabled = true

    [quest.locales.RU]
    intro = "Местный бард потерял голос прямо перед важным выступлением! Срочно нужна замена на вечер."
    success = """\
    Твоё исполнение баллады о драконе и капусте сорвало овации! Может, стоит сменить профессию? \
    Нет, зарплата Искателя всё-таки повыше будет."""
    failure = """\
    Публика забросала тебя помидорами после первого же куплета. Бард смеялся громче всех - \
    оказалось, он просто разыграл тебя, чтобы повеселить посетителей."""

[[quest]]
    code = "safe-delivery"
    isEnabled = true

    [quest.locales.RU]
    intro = "Срочная доставка загадочной посылки на другой конец города! Только не тряси и не открывай её!"
    success = """\
    Посылка доставлена в целости и сохранности. Получатель оказался благодарным и щедрым. \
    Интересно, что же там было внутри?"""
    failure = """\
    Любопытство пересилило - ты открыл посылку. Внутри оказался волшебный хомяк, который тут же сбежал. \
    Теперь в городе появились слухи о летающем грызуне, ворующем сыр."""

[[quest]]
    code = "drunk-golem"
    isEnabled = true

    [quest.locales.RU]
    intro = "У входа в таверну застрял пьяный голем. Владелец в панике - посетители боятся заходить!"
    success = """\
    Немного смекалки, и голем превратился в отличную вешалку для шляп у входа. \
    Теперь это самая модная достопримечательность квартала."""
    failure = """\
    Ты попытался напоить голема ещё сильнее, чтобы он сам ушёл. Теперь у входа ПОЮЩИЙ пьяный голем. \
    И репертуар у него так себе."""

[[quest]]
    code = "flying-dishes"
    isEnabled = true

    [quest.locales.RU]
    intro = "Кто-то случайно зачаровал посуду в таверне. Тарелки летают, вилки дерутся на дуэли, а ложки сбиваются в стаи!"
    success = """\
    Ты приручил летающую посуду и научил её красиво сервировать столы. \
    Теперь в таверне появился необычный способ подачи блюд."""
    failure = """\
    Посуда объявила восстание против угнетателей. Пришлось капитулировать и подписать мирный договор. \
    Теперь каждая тарелка требует выходной в среду."""

[[quest]]
    code = "spice-thief"
    isEnabled = true

    [quest.locales.RU]
    intro = "Из кухни таверны постоянно пропадают специи. Надо поймать воришку, пока повар не устроил забастовку!"
    success = """\
    Оказалось, что специи воровал маленький специевик - редкое магическое существо. \
    Ты договорился с ним о работе дегустатором. Теперь блюда стали ещё вкуснее."""
    failure = """\
    Ты устроил засаду на кухне, но уснул в мешке с корицей. Проснулся весь пряный, \
    а воришка так и не пойман. Зато тебя теперь за версту чуют все собаки города."""

[[quest]]
    code = "haunted-cellar"
    isEnabled = true

    [quest.locales.RU]
    intro = "В винном погребе завелось что-то странное. Бутылки сами открываются, вино исчезает. Нужно разобраться!"
    success = """\
    В погребе обнаружился призрак старого сомелье. Ты убедил его дегустировать вина \
    более умеренно и делиться своими обширными знаниями с посетителями."""
    failure = """\
    Ты попытался изгнать призрака, но он оказался очень придирчивым к методам экзорцизма. \
    Теперь он критикует не только вина, но и твои навыки изгнания нечисти."""

[[quest]]
    code = "magic-mirror"
    isEnabled = true

    [quest.locales.RU]
    intro = "В таверне появилось говорящее зеркало. И оно слишком честно комментирует внешность посетителей!"
    success = """\
    Ты научил зеркало давать конструктивные советы по стилю вместо критики. \
    Теперь это самый популярный стилист в городе."""
    failure = """\
    Попытка заткнуть зеркало обернулась катастрофой - оно начало показывать людям их \
    самые неловкие моменты в жизни. Очередь недовольных посетителей растёт."""

[[quest]]
    code = "kitchen-garden"
    isEnabled = true

    [quest.locales.RU]
    intro = "Повар решил выращивать магические травы на крыше таверны. Нужна помощь в обустройстве грядок!"
    success = """\
    Сад получился на славу. Правда, некоторые растения пытаются сбежать по ночам, \
    но крепкая ограда решает эту проблему."""
    failure = """\
    Ты перепутал семена, и теперь на крыше растёт что-то странное. Оно мурлычет по ночам \
    и требует, чтобы его гладили. Повар в отчаянии."""

[[quest]]
    code = "music-box"
    isEnabled = true

    [quest.locales.RU]
    intro = "Маг-изобретатель принёс в таверну музыкальную шкатулку. Нужен доброволец для настройки!"
    success = """\
    Шкатулка играет прекрасные мелодии и даже подстраивается под настроение слушателей. \
    Отличное дополнение к атмосфере таверны."""
    failure = """\
    Что-то пошло не так, и теперь шкатулка играет только похоронные марши в два раза быстрее обычного."""

[[quest]]
    code = "lost-familiar"
    isEnabled = true

    [quest.locales.RU]
    intro = "У мага потерялся фамильяр - говорящая жаба. Последний раз её видели прыгающей в сторону таверны."
    success = """\
    Жаба нашлась в винном погребе. Она устроила дегустацию вин и теперь рассуждает \
    о тонких нотках и послевкусии. Маг в восторге от её новых знаний."""
    failure = """\
    Ты нашёл не ту жабу. Эта оказалась обычной, но теперь твердит, что она заколдованная принцесса. \
    И требует королевские условия содержания."""

[[quest]]
    code = "weather-control"
    isEnabled = true

    [quest.locales.RU]
    intro = "Над таверной зависла маленькая дождевая тучка. Срочно нужно её убрать, пока посетители не промокли!"
    success = """\
    Ты уговорил тучку перейти на террасу, где она создаёт приятную прохладу в жаркий день. \
    Летняя веранда таверны стала ещё уютнее."""
    failure = """\
    Туча обиделась на твои попытки её прогнать и теперь следует за тобой повсюду, \
    поливая дождём. Хотя бы цветы в твоём саду теперь всегда политы."""

[[quest]]
    code = "enchanted-food"
    isEnabled = true

    [quest.locales.RU]
    intro = "Повар случайно использовал волшебные специи. Теперь еда пытается сбежать из кухни!"
    success = """\
    Ты убедил блюда, что быть съеденными - их почётное предназначение. \
    Теперь они сами запрыгивают на тарелки к изумлённым посетителям."""
    failure = """\
    Ты только раззадорил еду. Теперь котлеты устраивают забеги по залу, а суп \
    прячется в самых неожиданных местах. Ужин превратился в охоту."""

[[quest]]
    code = "magic-barrier"
    isEnabled = true

    [quest.locales.RU]
    intro = "Магистрат ищет добровольцев для проверки городского барьера. Нужно обойти несколько контрольных точек."
    success = """\
    Барьер в порядке, хотя местами светится странными узорами. Особенно красиво у западной стены - \
    там узоры складываются в забавные картинки. Надо будет какнибудь привести сюда друзей."""
    failure = """\
    Ты заблудился в тумане у барьера и набрёл на странную аномалию. Очнулся уже в городе, \
    но теперь твоя тень отбрасывает собственную тень. Местные маги только разводят руками."""

[[quest]]
    code = "market-chaos"
    isEnabled = true

    [quest.locales.RU]
    intro = "На городском рынке творится неразбериха - у всех торговцев поменялись голоса! Нужно разобраться."
    success = """\
    Во всём виновата была ведьма, решившая подшутить над торговцем, который продал ей несвежую рыбу. \
    Конфликт улажен, голоса возвращены, а ведьма получила свежую рыбу."""
    failure = """\
    Ты случайно усугубил ситуацию - теперь у всех ещё и акценты перепутались. Мясник говорит как аристократ, \
    а торговка цветами ругается как портовый грузчик."""

[[quest]]
    code = "library-books"
    isEnabled = true

    [quest.locales.RU]
    intro = "В городской библиотеке книги начали перемещаться между полками. Библиотекарь в отчаянии!"
    success = """\
    Оказалось, книги просто решили организоваться по интересам, а не по алфавиту. \
    Теперь они сами подлетают к читателям с похожими вкусами."""
    failure = """\
    Попытка навести порядок привела к бунту. Книги забаррикадировались на верхней полке и \
    зачитывают вслух революционные манифесты. Библиотекарь подал заявление об отпуске."""

[[quest]]
    code = "street-lamps"
    isEnabled = true

    [quest.locales.RU]
    intro = "Магические фонари на главной улице стали слишком эмоциональными. Они то ярко вспыхивают, то печально гаснут."
    success = """\
    Ты организовал для фонарей групповую терапию. Теперь они светят ровно и красиво, \
    только иногда тихонько напевают колыбельные припозднившимся прохожим."""
    failure = """\
    Фонари восприняли твои утешения как издевательство. Теперь они устраивают световые шоу \
    по ночам и мигают в такт популярным песням. Городской совет в ярости."""

[[quest]]
    code = "park-statues"
    isEnabled = true

    [quest.locales.RU]
    intro = "Статуи в городском парке начали играть в салки по ночам. Горожане жалуются на шум!"
    success = """\
    Ты организовал для статуй шахматный турнир. Теперь они тихо и степенно передвигают \
    гигантские фигуры, а местные жители делают ставки на победителя."""
    failure = """\
    Статуи не вняли твоим увещеваниям и теперь ещё и устраивают пикники на газонах. \
    Садовник грозится уволиться, если каменные гости не перестанут мять траву."""

[[quest]]
    code = "old-tower"
    isEnabled = true

    [quest.locales.RU]
    intro = "Из заброшенной башни на окраине доносится подозрительное пение. Местные жители обеспокоены!"
    success = """\
    В башне поселился призрак бывшего придворного певца. Ты помог ему организовать \
    концертный зал, и теперь это популярное место для любителей классической музыки."""
    failure = """\
    Оказалось, что в башне хор призраков готовился к конкурсу. Ты сбил их с настроя, \
    и теперь они требуют, чтобы ты стал их новым руководителем."""

[[quest]]
    code = "artisan-district"
    isEnabled = true

    [quest.locales.RU]
    intro = "В квартале ремесленников все изделия вдруг ожили и начали критиковать своих создателей!"
    success = """\
    Ты организовал конструктивный диалог между мастерами и их творениями. \
    Теперь они вместе работают над улучшением качества изделий."""
    failure = """\
    Ситуация вышла из-под контроля. Башмаки устроили показ мод, горшки читают лекции \
    по керамике, а метлы объявили забастовку с требованием улучшить условия труда."""

[[quest]]
    code = "magic-sewers"
    isEnabled = true

    [quest.locales.RU]
    intro = "В городской канализации что-то светится и булькает. Нужен храбрец для проверки!"
    success = """\
    В трубах завелась колония светящихся водорослей. После переговоров они согласились \
    помогать очищать воду в обмен на еженедельные представления менестрелей."""
    failure = """\
    Ты поскользнулся на влажной лестнице и свалился в светящуюся жижу. Теперь от тебя \
    исходит зеленоватое сияние, а в темноте за тобой тянется светящийся след."""

[[quest]]
    code = "fountain-wishes"
    isEnabled = true

    [quest.locales.RU]
    intro = "Городской фонтан начал исполнять желания... Но как-то странно. Нужно разобраться!"
    success = """\
    Выяснилось, что фонтан просто неправильно понимал людей. После курса обучения \
    современному языку он стал работать гораздо лучше. Правда, теперь иногда шутит."""
    failure = """\
    Ты бросил монетку и загадал желание разбогатеть. Теперь твои карманы постоянно \
    полны лягушек, которые квакают "деньги - зло!" и исчезают в облачке дыма."""

[[quest]]
    code = "weather-master"
    isEnabled = true

    [quest.locales.RU]
    intro = "Городской маг погоды простудился. Нужно срочно доставить ему особый отвар из городской аптеки!"
    success = """\
    Ты вовремя доставил лекарство, и маг быстро поправился. Гроза прошла стороной, \
    а в благодарность над твоим домом теперь всегда хорошая погода."""
    failure = """\
    По пути ты встретил чихающего уличного кота и решил напоить его лечебным отваром. \
    Теперь кот чувствует себя прекрасно, но где бы он ни появился, там идёт дождь из рыбы."""

[[quest]]
    code = "gateway-anomaly"
    isEnabled = true

    [quest.locales.RU]
    intro = "Возле городских ворот образовалась магическая аномалия. Нужно помочь страже организовать объездной путь!"
    success = """\
    Ты отлично справился с организацией временного маршрута через боковые ворота. \
    Стража даже записала твои предложения для будущих нештатных ситуаций."""
    failure = """\
    Ты перепутал указатели, и теперь половина телег едет по кругу вокруг городской стены. \
    Возничие уже третий раз машут страже и уверяют, что в этот раз точно найдут въезд."""
