[[raid]]
    isEnabled = true
    code = "wolfpack"

    [raid.locales.RU]
    intro = "Мудрые волки снова мудрят."
    description = """\
    С недавних пор охотники, вернувшиеся из леса, ведут себя странно. Они заявляют, что не выступают в цирке и \
    мучают горожан советами: "Не важно кто, важно кто!", "Лучше попробовать, чем не попробовать", \
    "Любят тихо, громко только предают". Расправьтесь с причиной этого безумства!\
    \n\nТип атаки: рубящий. Тип защиты: кожа."""

[[raid]]
    isEnabled = true
    code = "zombie_horde"

    [raid.locales.RU]
    intro = "Преступление и наказание и зомби"
    description = """\
    В городе недалеко от столицы два пьяных зомби напали на торговца лепёшками. Инцидент произошел поздно ночью, \
    кто накормил зомби мясом с вином и зачем ему это нужно - не установлено. Местные власти призывают смельчаков \
    устранить опасность!\
    \n\nТип атаки: дробящий и рубящий. Тип защиты: латы."""

[[raid]]
    isEnabled = true
    code = "myconid_colony"

    [raid.locales.RU]
    intro = "Подлючие микониды! Откуда у них разум?!"
    description = """\
    Грибники в опасности! Микониды действуют хитро: сначала награждают грибников едким душком на ногах, \
    а после заселяются в их свободные дома! От зловонного запаха ног умерло уже 6 семей! Помогите, люди добрые!\
    \n\nТип атаки: магическая. Тип защиты: магическая."""

[[raid]]
    isEnabled = true
    code = "maggeese_flock"

    [raid.locales.RU]
    intro = "Караул! Маггуси терроризируют деревню!"
    description = """\
    Переизбыток магии свёл некоторых гусей с ума! Они сбиваются в стаи и нападают на всех подряд. \
    Периодически жертвами становятся даже другие гуси! Крестьяне боятся за свою жизнь и \
    отказываются выходить работать в поля. Остановите этих тварей!\
    \nКстати, таверны Крезара с радостью заплатят вам за свежие маггусиные тушки.\
    \n\nТип атаки: магическая и рубящая. Тип защиты: ткань."""

