topRaidWeek = """\
游끥Top de todos los Exploradores en incursiones de la semana <code>${start_date} - ${end_date}</code>:

${top_personage_list}

Total de participantes: ${total_count}"""
topRaidWeekGroup = """\
游끥Top de Exploradores del grupo en incursiones de la semana <code>${start_date} - ${end_date}</code>:

${top_personage_list}

Total de participantes: ${total_count}"""
topRaidPosition = "${position}. ${personage_badge_with_name}: ${success_raids}/${all_raids}"
topGroupRaidWeek = """\
游끥Top de Grupos en incursiones de la semana <code>${start_date} - ${end_date}</code>:

${top_group_list}

Total de grupos: ${total_count}"""
topGroupRaidPosition = "${position}. ${group_badge_with_name}: ${success_raids}/${all_raids} (${score} puntos)"
topRaidEmpty = "Nadie particip칩 en incursiones durante el per칤odo seleccionado"
topList = """\
游늵Lista de tops disponibles:

游댫Tops de Exploradores:
游디Top de Exploradores en incursiones de la semana ${top_raid_week_command}
游디Top de Exploradores en incursiones de la semana ${top_raid_week_group_command}
丘뇞op de trabajadores del grupo ${top_work_group_command}
游눩Top de poder de Exploradores del grupo ${top_power_personage_command}
游눯Top de donadores del grupo ${top_donate_command}

游논Tops de Grupos:
游디Top de Grupos en incursiones de la semana ${top_group_raid_week_command}"""
topWorkerOfDayEmpty = "Todav칤a nadie ha sido elegido como el trabajador del grupo."
topWorkerOfDayGroup = """\
丘뇞op de trabajadores del grupo de todos los tiempos:

${top_personage_list}

Total de participantes: ${total_count}
"""
topWorkerPosition = "${position}. ${personage_badge_with_name}: ${work_count}"

topPowerPersonageGroup = """\
游눩Top de poder de los Exploradores del grupo:

${top_personage_list}

Total de participantes: ${total_count}
"""
topPowerPersonagePosition = "${position}. ${personage_badge_with_name}: ${power}"
topPersonageEmpty = "No hay participantes para mostrar"
topWorldRaidResearch = """\
游끥Top de Exploradores por contribuci칩n en la b칰squeda de incursi칩n mundial:

${top_personage_list}

Total de participantes: ${total_count}"""
topWorldRaidResearchPosition = "${position}. ${personage_badge_with_name}: ${contribution} ${optional_reward}"
topWorldRaidResearchReward = " +${money_icon}${reward}"
topWorldRaidResearchEmpty = "Nadie ha contribuido todav칤a en la b칰squeda de incursi칩n"
topDonateGroup = """\
游눯Top de donadores del grupo (<code>Temporada ${season_number}</code>):

${top_personage_list}

Total de participantes: ${total_count}"""
topDonatePosition = "${position}. ${personage_badge_with_name}: ${money_icon}${donate_money}"
topDonateEmpty = "A칰n nadie ha hecho donaciones en este grupo"
