contrabandFoundPrivateMessage = """\
<b>${contraband_name}</b>

Ты обнаружил потерянную контрабанду с Чёрного Рынка. Кажется кроме защитных механизмов тут ещё и какая-то неизвестная магия... \
Вскрывать самому крайне опасно, зато всегда можно отдать его владельцам за вознаграждение

Контрабанда окончательно разложится от воздействия магии через ${time_left}"""

commonChestName = "🗞Подозрительный свёрток"
uncommonChestName = "📦Запечатанный ящик"
rareChestName = "🔒Тяжёлый сейф"
epicChestName = "👁Шепчущий ларь"

forceOpenButton = "🔓 Вскрыть самому"
sellToMarketButton = "💰 Продать (${money_icon}${price})"
openAsReceiverButton = "🔧 Вскрыть инструментами"

openSuccess = [
    "Ловкость рук и никакого мошенничества!\n${rewards}",
    "Да ты ювелир!\n${rewards}",
    "Раз раз и готово!\n${rewards}",
]

openFailure = [
    "Контрабанда взорвалась у тебя в руках!\n${penalty}",
    "Из контрабанды вырвался клуб едкого дыма.\n${penalty}",
    "Вспышка света чуть не оставила тебя без пальцев.\n${penalty}",
]

penaltyGoldLoss = "-${money_icon}${amount}"
penaltyNothing = "Контрабанда уничтожена, но тебе повезло остаться в живых."

sellSuccess = "Ящик отправлен на чёрный рынок. +${money_icon}${sell_price}"

receiverNotification = """\
<b>${contraband_name}</b>.

Кажется <code>${finder}</code> нашёл контрабанду Чёрного Рынка и передал её владельцам, но они ничего не смогли сделать с дикой магией.

Тебе предоставят набор инструментов и возможность забрать часть содержимого, но всё может закончится неудачей.

Контрабанда окончательно разложится от воздействия магии через ${time_left}"""

echoToFinderSuccess = "📬 Новости с чёрного рынка: <code>${receiver}</code> успешно вскрыл твой <b>${contraband_name}</b>. Ну и пожалуйста. Ну и не нужно."
echoToFinderFailure = "📬 Новости с чёрного рынка: <code>${receiver}</code> попытался вскрыть твой <b>${contraband_name}</b>... и всё взорвалось."

contrabandExpired = "⏰ Контрабанда <b>${contraband_name}</b> разложилась под действием магии... в следующий раз будешь быстрее."

rewardGold = "+${money_icon}${amount}"
rewardItem = "<code>${item_name}</code>"
rewardEnergy = "+${amount}${energy_icon}"

contrabandAlreadyProcessed = "Этот ящик уже обработан."
contrabandExpiredError = "Ящик истёк и рассыпался в пыль."
noActiveContraband = "У тебя нет активной контрабанды."
