duelMustContainsMention = """\
    Выбери себе противника для дуэли! Для этого нужно ответить на сообщение соперника \
    либо упомянуть его в сообщении, например: <code>${duel_command} @user</code>.
    """
duelWithDifferentBot = [
    "Выбери себе в противники кого-нибудь поживее!" # TODO здесь можно добавить рандомный пинг игрока
]
duelWithThisBot = [
    "Не советую начинать драку с персоналом! Иначе в твоём пиве может оказаться специальная пенка от официанта"
]
duelWithYourself = "Нельзя устроить дуэль с самим собой!"
duelWithInitiatorNotEnoughMoney = [
    "Воу! Чтобы воспользоваться ареной тебе нужно хотя бы ${money_icon}${money_count}. Иди поработай для начала",
    "Вход в арену стоит ${money_icon}${money_count}, иди работать!",
    "Бой - привелегия богатых, а не бедных. Накопи ${money_icon}${money_count} и возвращайся.",
    "Кажется, этот бой тебе не по карману! Необходимо ${money_icon}${money_count}."
]
personageAlreadyStartDuel = "Вы уже начали другую дуэль! Дождитесь её окончания."
initDuel = """\
${init_duel_variation}
<i>-${duel_cost}${money_icon}</i>"""
initDuelVariation = [
    "Искатель ${mention_initiator_icon_with_name} вызывает на дуэль ${mention_acceptor_icon_with_name}.",
    """\
От ${mention_initiator_icon_with_name} прилетела перчатка в лицо \
${mention_acceptor_icon_with_name}!""",
    "Возьми себя в руки, ${mention_acceptor_icon_with_name}, и прими вызов от ${mention_initiator_icon_with_name}!",
    "${mention_initiator_icon_with_name} явно намеревается дать по щам ${mention_acceptor_icon_with_name}!",
    """\
Гоп стоп! ${mention_acceptor_icon_with_name} стопанули за углом таверны! ${mention_initiator_icon_with_name} \
- серьезная персона и не собирается церемониться на дуэли!""",
]
notDuelAcceptingPersonage = "Это не вас вызвали на дуэль!"
expiredDuel = [
    "Вызов на дуэль остался проигнорированным",
    "${mention_acceptor_icon_with_name}: Хочу иду на дуэль, хочу не иду, мне вообще пофиг!",
    "${mention_acceptor_icon_with_name} не может выйти на дуэль. Позовите позднее.",
    "${mention_acceptor_icon_with_name} наказала мама. Пока полы не будут помыты - дуэли не будет!",
]
declinedDuel = [
    "Принимающая сторона отклонила вызов!",
    "Ха! ${mention_initiator_icon_with_name}, ищи дурака для дуэли в другом месте!"
]
finishedDuel = [
    "Искатель ${mention_winner_icon_with_name} одержал верх над ${mention_loser_icon_with_name}",
    "${mention_loser_icon_with_name} размазали тонким слоем по брусчатке!",
    "Бой окончен! ${mention_winner_icon_with_name} явно сильнее ${mention_loser_icon_with_name}!",
    "Во время дуэли ${mention_winner_icon_with_name} легким движением руки отправляет спать ${mention_loser_icon_with_name}!",
    "В следующий раз ${mention_loser_icon_with_name} подумает дважды, прежде чем драться с ${mention_winner_icon_with_name}.",
    "Чики-брики и ${mention_winner_icon_with_name} в дамках!",
]
finishedDuelResult = """\
${finished_duel}

${time_icon}Раунды: ${rounds_count}
${winner_result}
${loser_result}"""
acceptDuelButton = "Принять вызов🗡"
declineDuelButton = "Отказаться👐"
duelWithUnknownUser = [
    """\
К сожалению, персонал не знает кому отправить вызов на дуэль. \
Возможно твой товарищ ещё не посещал данную таверну, а может сменил имя."""
]
duelIsLocked = "Дуэль обрабатывается, попробуйте позже."
personageDuelResult = """\
${winner_or_loser_icon}${personage_badge_with_name}: \
${remain_health}${health_icon} ${damage_dealt}${attack_icon} (${crits_count}${crit_icon}${dodges_count}${dodge_icon}) ${time_icon}${turns_count}"""
duelAlreadyFinished = "Дуэль была завершена ранее, но результат не отразился по причине ошибки системы. Приносим свои извинения."
