itemName = "${modifier}${object}"
fullItem = "${slots}${rarity_icon}${broken_icon} ${item} ${characteristics}"
shortItem = "${rarity_icon}${broken_icon} ${item} ${characteristics}"
shortItemWithoutCharacteristics = "${rarity_icon}${broken_icon} ${item}"
characteristics = "${not_zero_health}${not_zero_attack}${not_zero_defense}"
attack = "${attack_icon}${attack_value}"
defense = "${defense_icon}${defense_value}"
health = "${health_icon}${health_value}"
itemInBag = "${full_item} ${put_on_command}"
equippedItem = "${full_item} ${take_off_command}"
personageFreeSlot = "${slot} <i>Пусто</i>"

inventory = """\
<b>👤Снаряжение:</b>
${equipped_items_and_free_slots}

<b>🎒Рюкзак (${items_in_bag_count}/${max_items_in_bag}):</b>
${items_in_bag}"""

personageMissingItem = "У вас нет такого предмета"
alreadyEquipped = "Вы уже экипировали данный предмет"
alreadyTakenOff = "Данный предмет не экиперован"
notEnoughSpaceInBag = "В рюкзаке недостаточно места, чтобы снять предмет"
notEnoughSpaceOnPutOnItem = "В рюкзаке недостаточно места, чтобы снять предметы: ${slots}"
successPutOn = "Успешно экипировано: ${item}"
successPutOnWithTakenOff = """\
Снято:
${taken_off_items}

Экипировано:
${item}"""
successTakeOff = "Успешно снято: ${item}"
